# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Event Management Service
"""
from typing import Dict, List, Optional
from datetime import datetime
import uuid
import logging

logger = logging.getLogger(__name__)

class EventService:
    """Manages event CRUD operations"""
    
    def __init__(self, db_manager):
        self.db_manager = db_manager
        self.db = db_manager
        logger.info("EventService initialized with database connection")
    
    # def create_event(self, event_data: Dict, created_by: str = 'chatbot') -> Dict:
    #     """Create new event and APR entry"""
    #     conn = None
    #     try:
    #         conn = self.db_manager.get_connection()
    #         cursor = conn.cursor()
            
    #         # Start transaction
    #         conn.start_transaction()
            
    #         # Determine financial year
    #         event_date = datetime.strptime(event_data['event_date'], '%Y-%m-%d')
    #         if event_date.month >= 4:
    #             fy = f"{event_date.year}-{event_date.year + 1}"
    #         else:
    #             fy = f"{event_date.year - 1}-{event_date.year}"
            
    #         # Get institution and artist details
    #         cursor.execute(
    #             "SELECT institution_name FROM institution_list WHERE sid = %s",
    #             (event_data['institution_id'],)
    #         )
    #         inst_result = cursor.fetchone()
    #         institution_name = inst_result[0] if inst_result else ''
            
    #         cursor.execute(
    #             "SELECT name FROM artists_list WHERE tid = %s",
    #             (event_data['artist_id'],)
    #         )
    #         artist_result = cursor.fetchone()
    #         artist_name = artist_result[0] if artist_result else ''
            
    #         # Insert into event_list
    #         event_query = """
    #             INSERT INTO event_list (
    #                 title, start_date, end_date, event_time, event_category,
    #                 state, city, institution, artist, venue,
    #                 attendees, budget, added_by, added_date, updated_date,
    #                 event_status, status, fy, chapter
    #             ) VALUES (
    #                 %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
    #                 %s, %s, %s, %s, %s, %s, %s, %s, %s
    #             )
    #         """
            
    #         event_title = f"{event_data.get('event_module', 'Event')} - {artist_name}"
    #         current_date = datetime.now().strftime('%Y-%m-%d')
            
    #         event_values = (
    #             event_title,
    #             event_data['event_date'],
    #             event_data['event_date'],
    #             event_data.get('event_time', ''),
    #             event_data.get('event_module', ''),
    #             event_data['state'],
    #             event_data['city'],
    #             str(event_data['institution_id']),
    #             str(event_data['artist_id']),
    #             event_data.get('venue', ''),
    #             event_data.get('attendees', ''),
    #             event_data.get('budget', 0),
    #             created_by,
    #             current_date,
    #             current_date,
    #             'Pending',
    #             1,
    #             fy,
    #             event_data.get('chapter', '')
    #         )
            
    #         cursor.execute(event_query, event_values)
    #         event_id = cursor.lastrowid
            
    #         # Create APR payment request
    #         request_id = self._generate_request_id()
    #         custom_apr = f"APR-{event_id}-{datetime.now().strftime('%Y%m%d')}"
            
    #         apr_query = """
    #             INSERT INTO apr_payment_request (
    #                 request_id, artist_id, event_id, custom_apr,
    #                 event_date, time_duration, institution, chapter,
    #                 students, fc, created_by, dt_created, del, updated_by
    #             ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 0, %s)
    #         """
            
    #         apr_values = (
    #             request_id,
    #             str(event_data['artist_id']),
    #             str(event_id),
    #             custom_apr,
    #             event_data['event_date'],
    #             event_data.get('event_time', ''),
    #             institution_name,
    #             event_data.get('chapter', ''),
    #             event_data.get('attendees', ''),
    #             '',  # fc field
    #             created_by,
    #             current_date,
    #             created_by
    #         )
            
    #         cursor.execute(apr_query, apr_values)
            
    #         # Commit transaction
    #         conn.commit()
            
    #         logger.info(f"Event created successfully: ID={event_id}, APR={request_id}")
            
    #         return {
    #             'success': True,
    #             'event_id': event_id,
    #             'request_id': request_id,
    #             'custom_apr': custom_apr,
    #             'message': 'Event created successfully',
    #             'artist_name': artist_name,
    #             'institution_name': institution_name,
    #             'event_date': event_data['event_date']
    #         }
            
    #     except Exception as e:
    #         if conn:
    #             conn.rollback()
    #         logger.error(f"Error creating event: {e}")
    #         return {
    #             'success': False,
    #             'error': str(e),
    #             'message': f'Failed to create event: {str(e)}'
    #         }
    #     finally:
    #         if conn:
    #             cursor.close()
    #             conn.close()
    # Code Generated by Sidekick is for learning and experimentation purposes only.
# Code Generated by Sidekick is for learning and experimentation purposes only.
# Code Generated by Sidekick is for learning and experimentation purposes only.
    def create_event(self, event_data: dict) -> dict:
        """
        Create a new event
        
        Args:
            event_data: Dictionary containing event information
            
        Returns:
            Dictionary with success status and event_id or error
        """
        try:
            # Handle both 'start_date' and 'event_date' field names
            event_date = event_data.get('event_date') or event_data.get('start_date')
            if not event_date:
                logger.error("Missing event_date or start_date")
                return {
                    'success': False,
                    'error': 'Missing event date',
                    'message': 'Event date is required'
                }
            
            # Determine financial year
            event_date_obj = datetime.strptime(event_date, '%Y-%m-%d')
            if event_date_obj.month >= 4:
                fy = f"{event_date_obj.year}-{event_date_obj.year + 1}"
            else:
                fy = f"{event_date_obj.year - 1}-{event_date_obj.year}"
            
            # Get next ID (since AUTO_INCREMENT isn't working)
            max_id_query = "SELECT COALESCE(MAX(id), 0) + 1 as next_id FROM event_list"
            id_result = self.db.fetch_one(max_id_query)
            next_id = id_result['next_id'] if id_result else 1
            
            # NOW include 'id' in the INSERT
            query = """
            INSERT INTO event_list (
                id, title, start_date, end_date, event_time, event_category,
                state, city, institution, artist, venue,
                attendees, budget, added_by, added_date, updated_date,
                event_status, status, fy
            ) VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s, %s, %s, %s
            )
            """
            
            current_date = datetime.now().strftime('%Y-%m-%d')
            event_title = event_data.get('title', f"Event at {event_data.get('institution_name', 'Institution')}")
            
            values = (
                next_id,  # <-- Add the ID here
                event_title,
                event_date,
                event_data.get('end_date', event_date),
                event_data.get('event_time', '18:00'),
                event_data.get('module_name', 'Lecture Demonstration'),
                event_data.get('state', ''),
                event_data.get('city', ''),
                str(event_data.get('institution_id', '')),
                str(event_data.get('artist_id', '')),
                event_data.get('venue', event_data.get('institution_name', '')),
                event_data.get('attendees', 100),
                event_data.get('budget', 0),
                event_data.get('created_by', 'System'),
                current_date,
                current_date,
                'Pending',
                1,
                fy
            )
            
            # Execute query
            result = self.db.execute_query(query, values, commit=True)
            
            # Check if query was successful
            if not result or not result.get('success'):
                error_msg = result.get('error', 'Unknown database error') if result else 'Database query failed'
                logger.error(f"Failed to insert event: {error_msg}")
                return {
                    'success': False,
                    'error': error_msg,
                    'message': f'Failed to create event: {error_msg}'
                }
            
            # Use the generated ID
            event_id = next_id
            
            logger.info(f"Event created successfully with ID: {event_id}")
            
            # Try to create APR automatically
            apr_result = self.create_apr(event_id, event_data)
            
            return {
                'success': True,
                'event_id': event_id,
                'message': f'Event created with ID: {event_id}',
                'apr': apr_result
            }
            
        except Exception as e:
            logger.error(f"Error creating event: {e}", exc_info=True)
            return {
                'success': False,
                'error': str(e),
                'message': f'Failed to create event: {e}'
            }

# Code Generated by Sidekick is for learning and experimentation purposes only.
    def create_apr(self, event_id: int, event_data: dict) -> Optional[dict]:
        """
        Create Artist Payment Request (APR)
        
        Args:
            event_id: ID of the created event
            event_data: Event information
            
        Returns:
            Dictionary with APR details or None if failed
        """
        try:
            # Generate APR request ID
            event_date = event_data.get('event_date') or event_data.get('start_date', '')
            request_id = self._generate_request_id()
            custom_apr = f"APR-{event_id}-{datetime.now().strftime('%Y%m%d')}"
            
            # Calculate payment amount (example logic)
            base_amount = 10000  # Base payment
            attendee_bonus = (event_data.get('attendees', 100) // 100) * 1000
            total_amount = base_amount + attendee_bonus
            
            current_date = datetime.now().strftime('%Y-%m-%d')
            
            # Use correct table name: apr_payment_request
            query = """
            INSERT INTO apr_payment_request (
                request_id, artist_id, event_id, custom_apr,
                event_date, time_duration, institution, 
                students, created_by, dt_created, del, updated_by
            ) VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 0, %s
            )
            """
            
            values = (
                request_id,
                str(event_data.get('artist_id', '')),
                str(event_id),
                custom_apr,
                event_date,
                event_data.get('event_time', ''),
                event_data.get('institution_name', ''),
                event_data.get('attendees', 100),
                event_data.get('created_by', 'System'),
                current_date,
                event_data.get('created_by', 'System')
            )
            
            result = self.db.execute_query(query, values, commit=True)
            
            if not result or not result.get('success'):
                logger.error(f"Failed to create APR: {result.get('error') if result else 'Unknown error'}")
                return None
            
            logger.info(f"APR created: {request_id}")
            
            return {
                'request_id': request_id,
                'custom_apr': custom_apr,
                'amount': total_amount,
                'status': 'Pending'
            }
            
        except Exception as e:
            logger.error(f"Error creating APR: {e}", exc_info=True)
            return None

    def _generate_request_id(self) -> str:
        """Generate unique request ID"""
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        random_suffix = uuid.uuid4().hex[:6].upper()
        return f"REQ-{timestamp}-{random_suffix}"
    
    def get_event_details(self, event_id: int) -> Optional[Dict]:
        """Get complete event details"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = """
                SELECT 
                    e.*,
                    a.name as artist_name,
                    a.art_form,
                    a.email as artist_email,
                    a.phone as artist_phone,
                    i.institution_name,
                    i.email as institution_email,
                    i.phone as institution_phone,
                    apr.request_id,
                    apr.custom_apr
                FROM event_list e
                LEFT JOIN artists_list a ON e.artist = a.tid
                LEFT JOIN institution_list i ON e.institution = i.sid
                LEFT JOIN apr_payment_request apr ON apr.event_id = e.id
                WHERE e.id = %s
            """
            
            cursor.execute(query, (event_id,))
            return cursor.fetchone()
            
        except Exception as e:
            logger.error(f"Error fetching event details: {e}")
            return None
        finally:
            if conn:
                cursor.close()
                conn.close()
    
    
    # Code Generated by Sidekick is for learning and experimentation purposes only.
    def create_apr(self, event_id: int, event_data: dict) -> dict:
        """
        Create Artist Payment Request (APR)
        
        Args:
            event_id: ID of the created event
            event_data: Event information
            
        Returns:
            Dictionary with APR details or None if failed
        """
        try:
            # Generate APR request ID
            event_date = event_data.get('event_date') or event_data.get('start_date', '')
            request_id = f"APR-{event_id}-{event_date.replace('-', '')}"
            
            # Calculate payment amount (example logic)
            base_amount = 10000  # Base payment
            attendee_bonus = (event_data.get('attendees', 100) // 100) * 1000
            total_amount = base_amount + attendee_bonus
            
            query = """
            INSERT INTO artist_payment_requests (
                request_id, event_id, artist_id, artist_name,
                event_date, institution_name, city, state,
                amount, status, created_at
            ) VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW()
            )
            """
            
            values = (
                request_id,
                event_id,
                event_data.get('artist_id'),
                event_data.get('artist_name'),
                event_date,
                event_data.get('institution_name'),
                event_data.get('city'),
                event_data.get('state'),
                total_amount,
                'Pending'
            )
            
            #cursor = self.db.cursor()
            #cursor.execute(query, values)
            #self.db.commit()
            #cursor.close()
            result = self.db.execute_query(query, values, commit=True)
            
            logger.info(f"APR created: {request_id}")
            
            return {
                'request_id': request_id,
                'amount': total_amount,
                'status': 'Pending',
                'custom_apr': f"APR-{event_id}"
            }
            
        except Exception as e:
            logger.error(f"Error creating APR: {e}", exc_info=True)
            self.db.rollback()
            return None

    def search_events(self, filters: Dict) -> List[Dict]:
        """Search events with filters"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = """
                SELECT 
                    e.*,
                    a.name as artist_name,
                    i.institution_name
                FROM event_list e
                LEFT JOIN artists_list a ON e.artist = a.tid
                LEFT JOIN institution_list i ON e.institution = i.sid
                WHERE e.status = 1
            """
            params = []
            
            if filters.get('search'):
                query += """ AND (
                    e.title LIKE %s OR 
                    a.name LIKE %s OR 
                    i.institution_name LIKE %s
                )"""
                search_pattern = f"%{filters['search']}%"
                params.extend([search_pattern] * 3)
            
            if filters.get('status'):
                query += " AND e.event_status = %s"
                params.append(filters['status'])
            
            if filters.get('date_from'):
                query += " AND e.start_date >= %s"
                params.append(filters['date_from'])
            
            if filters.get('date_to'):
                query += " AND e.start_date <= %s"
                params.append(filters['date_to'])
            
            if filters.get('state'):
                query += " AND e.state = %s"
                params.append(filters['state'])
            
            query += " ORDER BY e.start_date DESC LIMIT 50"
            
            cursor.execute(query, params)
            return cursor.fetchall()
            
        except Exception as e:
            logger.error(f"Error searching events: {e}")
            return []
        finally:
            if conn:
                cursor.close()
                conn.close()
    
    def update_event_status(self, event_id: int, status: str, updated_by: str) -> bool:
        """Update event status"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor()
            
            query = """
                UPDATE event_list 
                SET event_status = %s, 
                    updated_by = %s, 
                    updated_date = %s
                WHERE id = %s
            """
            cursor.execute(query, (
                status, 
                updated_by, 
                datetime.now().strftime('%Y-%m-%d'), 
                event_id
            ))
            conn.commit()
            
            logger.info(f"Event {event_id} status updated to {status}")
            return True
            
        except Exception as e:
            if conn:
                conn.rollback()
            logger.error(f"Error updating event status: {e}")
            return False
        finally:
            if conn:
                cursor.close()
                conn.close()
    
    def get_dashboard_stats(self) -> Dict:
        """Get statistics for dashboard"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            stats = {}
            
            # Total events
            cursor.execute("SELECT COUNT(*) as total FROM event_list WHERE status = 1")
            stats['total_events'] = cursor.fetchone()['total']
            
            # Events by status
            cursor.execute("""
                SELECT event_status, COUNT(*) as count 
                FROM event_list 
                WHERE status = 1 
                GROUP BY event_status
            """)
            stats['events_by_status'] = cursor.fetchall()
            
            # Upcoming events (next 30 days)
            cursor.execute("""
                SELECT COUNT(*) as count 
                FROM event_list 
                WHERE status = 1 
                AND event_status = 'Pending'
                AND start_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
            """)
            stats['upcoming_events'] = cursor.fetchone()['count']
            
            # Recent events
            cursor.execute("""
                SELECT e.*, a.name as artist_name, i.institution_name
                FROM event_list e
                LEFT JOIN artists_list a ON e.artist = a.tid
                LEFT JOIN institution_list i ON e.institution = i.sid
                WHERE e.status = 1
                ORDER BY e.added_date DESC
                LIMIT 10
            """)
            stats['recent_events'] = cursor.fetchall()
            
            # Events by state
            cursor.execute("""
                SELECT state, COUNT(*) as count
                FROM event_list
                WHERE status = 1
                GROUP BY state
                ORDER BY count DESC
                LIMIT 10
            """)
            stats['events_by_state'] = cursor.fetchall()
            
            return stats
            
        except Exception as e:
            logger.error(f"Error fetching dashboard stats: {e}")
            return {}
        finally:
            if conn:
                cursor.close()
                conn.close()
