# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Voice Service - OpenAI Whisper & TTS Integration
Handles speech-to-text and text-to-speech using OpenAI APIs
"""

from openai import OpenAI
import os
import logging
from pathlib import Path
import tempfile
import time

logger = logging.getLogger(__name__)

class VoiceService:
    """Handles voice-to-text and text-to-speech using OpenAI APIs"""
    
    def __init__(self, api_key: str):
        """
        Initialize Voice Service
        
        Args:
            api_key: OpenAI API key
        """
        self.client = OpenAI(api_key=api_key)
        self.temp_dir = Path(tempfile.gettempdir()) / "spicmacay_voice"
        self.temp_dir.mkdir(exist_ok=True)
        logger.info(f"VoiceService initialized, temp dir: {self.temp_dir}")
    
    def transcribe_audio(self, audio_file_path: str, language: str = "en") -> dict:
        """
        Transcribe audio to text using OpenAI Whisper
        
        Args:
            audio_file_path: Path to audio file
            language: Language code (default: "en")
            
        Returns:
            Dictionary with transcription result
        """
        try:
            logger.info(f"Transcribing audio file: {audio_file_path}")
            
            with open(audio_file_path, "rb") as audio_file:
                transcript = self.client.audio.transcriptions.create(
                    model="whisper-1",
                    file=audio_file,
                    language=language,
                    response_format="json"
                )
            
            logger.info(f"Transcription successful: {transcript.text}")
            
            return {
                'success': True,
                'text': transcript.text,
                'language': language
            }
            
        except Exception as e:
            logger.error(f"Error transcribing audio: {e}", exc_info=True)
            return {
                'success': False,
                'error': str(e),
                'text': ''
            }
    
    def text_to_speech(self, text: str, voice: str = "nova", speed: float = 1.0) -> dict:
        """
        Convert text to speech using OpenAI TTS
        
        Args:
            text: Text to convert to speech
            voice: Voice to use (alloy, echo, fable, onyx, nova, shimmer)
            speed: Speed of speech (0.25 to 4.0)
            
        Returns:
            Dictionary with audio file path
        """
        try:
            logger.info(f"Converting text to speech (voice={voice}, speed={speed})")
            
            # Generate unique filename
            timestamp = int(time.time() * 1000)
            audio_filename = f"tts_{timestamp}.mp3"
            audio_path = self.temp_dir / audio_filename
            
            # Generate speech
            response = self.client.audio.speech.create(
                model="tts-1",  # Use tts-1-hd for higher quality (slower)
                voice=voice,
                input=text[:4096],  # OpenAI limit
                speed=speed
            )
            
            # Save to file
            response.stream_to_file(str(audio_path))
            
            logger.info(f"TTS successful: {audio_path}")
            
            return {
                'success': True,
                'audio_path': str(audio_path),
                'audio_filename': audio_filename,
                'voice': voice,
                'duration': len(text) / 15  # Rough estimate
            }
            
        except Exception as e:
            logger.error(f"Error generating speech: {e}", exc_info=True)
            return {
                'success': False,
                'error': str(e),
                'audio_path': None
            }
    
    def cleanup_old_files(self, max_age_hours: int = 24):
        """
        Clean up old temporary audio files
        
        Args:
            max_age_hours: Maximum age of files to keep (default: 24 hours)
        """
        try:
            current_time = time.time()
            max_age_seconds = max_age_hours * 3600
            
            deleted_count = 0
            for file_path in self.temp_dir.glob("*.mp3"):
                if current_time - file_path.stat().st_mtime > max_age_seconds:
                    file_path.unlink()
                    deleted_count += 1
            
            if deleted_count > 0:
                logger.info(f"Cleaned up {deleted_count} old audio files")
                    
        except Exception as e:
            logger.error(f"Error cleaning up files: {e}")
