# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Chat Routes for SPIC MACAY Event Agent
"""
from flask import Blueprint, request, jsonify, current_app, session
from app.models.agent import SPICMacayAgent
from app.models.main_agent import ConversationalAgent
from app.models.database import DatabaseManager, DatabaseValidator
from app.services.event_service import EventService
from app.models.notifications import NotificationService
import logging
import uuid

logger = logging.getLogger(__name__)

chat_bp = Blueprint('chat', __name__)

# Global instances (initialized per request)
agents = {}

def get_agent(session_id):
    """Get or create agent for session"""
    if session_id not in agents:
        db_manager = DatabaseManager(current_app.config['DB_CONFIG'])
        db_validator = DatabaseValidator(db_manager)
        event_service = EventService(db_manager)
        notification_service = NotificationService(current_app.config['SMTP_CONFIG'])
        
        agents[session_id] = SPICMacayAgent(
            api_key=current_app.config['OPENAI_API_KEY'],
            model=current_app.config['OPENAI_MODEL'],
            db_validator=db_validator,
            event_service=event_service,
            notification_service=notification_service
        )
        
               # This is where the magic happens!
        # ConversationalAgent.__init__ is called here
        #agents[session_id] = ConversationalAgent(
            #api_key=current_app.config['OPENAI_API_KEY'],
          
          
            #db_manager=db_manager,
            #event_service=event_service,
            #notification_service=notification_service
            #)
    
    return agents[session_id]

@chat_bp.route('/start', methods=['POST'])
def start_chat():
    """Start new chat session"""
    try:
        session_id = str(uuid.uuid4())
        agent = get_agent(session_id)
        
        greeting = agent.start_conversation()
        
        return jsonify({
            'success': True,
            'session_id': session_id,
            'message': greeting
        })
        
    except Exception as e:
        logger.error(f"Error starting chat: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@chat_bp.route('/message', methods=['POST'])
def send_message():
    """Send message to chat agent"""
    try:
        data = request.json
        session_id = data.get('session_id')
        message = data.get('message')
        
        if not session_id or not message:
            return jsonify({
                'success': False,
                'error': 'session_id and message are required'
            }), 400
        
        agent = get_agent(session_id)
        response = agent.process_message(message)
        
        return jsonify({
            'success': True,
            'response': response
        })
        
    except Exception as e:
        logger.error(f"Error processing message: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@chat_bp.route('/end', methods=['POST'])
def end_chat():
    """End chat session"""
    try:
        data = request.json
        session_id = data.get('session_id')
        
        if session_id in agents:
            del agents[session_id]
        
        return jsonify({
            'success': True,
            'message': 'Chat session ended'
        })
        
    except Exception as e:
        logger.error(f"Error ending chat: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500
