# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
SPIC MACAY Event Agent - Application Entry Point
"""
import os
import sys
import io
import logging
from dotenv import load_dotenv

# ── Force UTF-8 on Windows before ANY logging happens ─────────────────────── #
# Windows defaults to CP1252 which can't encode many Unicode chars in doc names.
if sys.platform == 'win32':
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    if hasattr(sys.stderr, 'reconfigure'):
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# Root logger: replace any existing StreamHandlers with UTF-8-safe ones
_root = logging.getLogger()
for _h in list(_root.handlers):
    if isinstance(_h, logging.StreamHandler) and hasattr(_h, 'stream'):
        try:
            _h.stream = io.TextIOWrapper(
                _h.stream.buffer, encoding='utf-8', errors='replace', line_buffering=True
            )
        except Exception:
            pass

# Load environment variables
load_dotenv()

# Import app factory
from app import create_app
from waitress import serve

# Create Flask app
app = create_app()

if __name__ == '__main__':
    port = int(os.getenv('PORT', 10000))
    debug = os.getenv('DEBUG', 'False').lower() == 'true'
    
    print("=" * 60)
    print("🎭 SPIC MACAY Conversational Event Agent")
    print("=" * 60)
    print(f"Environment: {'Development' if debug else 'Production'}")
    print(f"Port: {port}")
    print(f"Chat Interface: http://localhost:{port}")
    print(f"Dashboard: http://localhost:{port}/dashboard")
    print("=" * 60)
    print()
    
    # Configure logging with UTF-8 encoding
    log_handler = logging.StreamHandler(sys.stdout)
    log_handler.setLevel(logging.INFO)
    
    # Set formatter
    formatter = logging.Formatter(
        '[%(asctime)s] %(levelname)s in %(name)s: %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    log_handler.setFormatter(formatter)
    
    # Configure app logger
    app.logger.addHandler(log_handler)
    app.logger.setLevel(logging.INFO)
    
    # Configure other loggers
    logging.getLogger('app').setLevel(logging.INFO)
    logging.getLogger('app.models').setLevel(logging.INFO)
    
    # Check if running on Windows
    if sys.platform == 'win32' and not debug:
        # Use Waitress for Windows production
        try:
            from waitress import serve
            print("Using Waitress server (Windows)")
            print("Press CTRL+C to quit")
            serve(app, host='0.0.0.0', port=port, threads=4)
        except ImportError:
            print("Waitress not found, using Flask development server")
            serve(app, host='0.0.0.0', port=port, threads=4)
#            app.run(host='0.0.0.0', port=port, debug=debug)
    else:
        # Use Flask development server
        app.run(host='0.0.0.0', port=port, debug=debug)
