# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Extract database schema from existing MySQL database
FIXED: Handles table names with hyphens and special characters
"""

import mysql.connector
from dotenv import load_dotenv
import os
import json

load_dotenv()

print("🔍 Extracting Database Schema\n")
print("="*80 + "\n")

try:
    # Connect to database
    conn = mysql.connector.connect(
        host=os.getenv('DB_HOST', 'localhost'),
        database=os.getenv('DB_NAME', 'spic_macay'),
        user=os.getenv('DB_USER', 'root'),
        password=os.getenv('DB_PASSWORD', ''),
        port=int(os.getenv('DB_PORT', 3306))
    )
    
    cursor = conn.cursor(dictionary=True)
    
    print(f"✅ Connected to database: {os.getenv('DB_NAME')}\n")
    
    # Get all tables
    cursor.execute("SHOW TABLES")
    tables = cursor.fetchall()
    
    table_key = [k for k in tables[0].keys()][0] if tables else None
    
    print(f"📊 Found {len(tables)} tables:\n")
    
    schema_info = {}
    
    for table_row in tables:
        table_name = table_row[table_key]
        print(f"\n{'='*80}")
        print(f"📋 Table: {table_name}")
        print('='*80)
        
        # Use backticks to escape table names with special characters
        escaped_table = f"`{table_name}`"
        
        try:
            # Get table structure
            cursor.execute(f"DESCRIBE {escaped_table}")
            columns = cursor.fetchall()
            
            schema_info[table_name] = {
                'columns': columns,
                'sample_row': None,
                'row_count': 0
            }
            
            print("\nColumns:")
            print("-"*80)
            print(f"{'Field':<30} {'Type':<25} {'Null':<6} {'Key':<6} {'Default':<15} {'Extra'}")
            print("-"*80)
            
            for col in columns:
                default_val = str(col['Default'])[:15] if col['Default'] is not None else 'NULL'
                print(f"{col['Field']:<30} {col['Type']:<25} {col['Null']:<6} {col['Key']:<6} {default_val:<15} {col['Extra']}")
            
            # Get row count
            cursor.execute(f"SELECT COUNT(*) as count FROM {escaped_table}")
            count = cursor.fetchone()
            row_count = count['count']
            schema_info[table_name]['row_count'] = row_count
            print(f"\n📊 Total rows: {row_count}")
            
            # Get sample row
            if row_count > 0:
                cursor.execute(f"SELECT * FROM {escaped_table} LIMIT 1")
                sample = cursor.fetchone()
                
                if sample:
                    schema_info[table_name]['sample_row'] = sample
                    print("\n📝 Sample Row:")
                    print("-"*80)
                    for key, value in sample.items():
                        # Truncate long values
                        val_str = str(value)
                        if len(val_str) > 100:
                            val_str = val_str[:100] + "..."
                        print(f"  {key}: {val_str}")
            else:
                print("\n⚠️  No data in this table yet")
            
        except mysql.connector.Error as e:
            print(f"\n❌ Error reading table {table_name}: {e}")
            continue
    
    # Save schema to file
    print("\n" + "="*80)
    print("\n💾 Saving schema to 'my_database_schema.json'...")
    
    # Convert to JSON-serializable format
    json_schema = {}
    for table_name, info in schema_info.items():
        json_schema[table_name] = {
            'columns': [
                {
                    'Field': col['Field'],
                    'Type': col['Type'],
                    'Null': col['Null'],
                    'Key': col['Key'],
                    'Default': str(col['Default']) if col['Default'] is not None else None,
                    'Extra': col['Extra']
                }
                for col in info['columns']
            ],
            'sample_row': {k: str(v)[:200] for k, v in info['sample_row'].items()} if info['sample_row'] else None,
            'row_count': info['row_count']
        }
    
    with open('my_database_schema.json', 'w', encoding='utf-8') as f:
        json.dump(json_schema, f, indent=2, ensure_ascii=False)
    
    print("✅ Schema saved to 'my_database_schema.json'!\n")
    
    print("="*80)
    print("\n📋 SUMMARY FOR CUSTOMIZATION:")
    print("="*80)
    
    # Identify main tables
    event_tables = [name for name in schema_info.keys() if 'event' in name.lower() or 'programme' in name.lower()]
    artist_tables = [name for name in schema_info.keys() if 'artist' in name.lower()]
    institution_tables = [name for name in schema_info.keys() if 'institution' in name.lower()]
    
    if event_tables:
        print("\n🎯 EVENT TABLES FOUND:")
        for table_name in event_tables:
            print(f"  • {table_name}")
            info = schema_info[table_name]
            
            required_fields = [col['Field'] for col in info['columns'] 
                             if col['Null'] == 'NO' and col['Extra'] != 'auto_increment']
            
            if required_fields:
                print(f"\n    Required fields (NOT NULL):")
                for field in required_fields:
                    print(f"      ✓ {field}")
            
            optional_fields = [col['Field'] for col in info['columns'] 
                             if col['Null'] == 'YES' and col['Extra'] != 'auto_increment']
            
            if optional_fields:
                print(f"\n    Optional fields:")
                for field in optional_fields[:10]:  # Show first 10
                    print(f"      - {field}")
                if len(optional_fields) > 10:
                    print(f"      ... and {len(optional_fields) - 10} more")
    
    if artist_tables:
        print("\n🎨 ARTIST TABLES FOUND:")
        for table_name in artist_tables:
            print(f"  • {table_name} ({schema_info[table_name]['row_count']} rows)")
    
    if institution_tables:
        print("\n🏛️ INSTITUTION TABLES FOUND:")
        for table_name in institution_tables:
            print(f"  • {table_name} ({schema_info[table_name]['row_count']} rows)")
    
    print("\n" + "="*80)
    print("\n📄 FILES CREATED:")
    print("  ✓ my_database_schema.json (full schema)")
    print("\n📤 Next step: Share 'my_database_schema.json' or copy the output above")
    print("="*80 + "\n")
    
    cursor.close()
    conn.close()
    
    print("✅ Schema extraction complete!\n")

except mysql.connector.Error as e:
    print(f"❌ Database error: {e}")
    print("\nPlease check:")
    print("  1. MySQL is running: net start | findstr MySQL")
    print("  2. .env file has correct credentials")
    print(f"  3. Database '{os.getenv('DB_NAME')}' exists")
    print("\nTo check database:")
    print("  mysql -u root -p")
    print("  SHOW DATABASES;")
except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
