"""The end-to-end check script, exercised offline with stand-ins."""
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from helpers import FakeLLM  # noqa: E402
from real_world import POSTERS  # noqa: E402

import e2e_check  # noqa: E402

ENV_LIKE_YOURS = """# Code Generated by Sidekick
FLASK_ENV=production
SECRET_KEY=your-secret-key-here-change-in-production
OPENAI_API_KEY=sk-proj-not-a-real-key-000000000000
MYSQL_HOST=https://203.0.113.10/
MYSQL_USER=root
MYSQL_PASSWORD=not-real
DB_HOST=localhost
DB_USER=spicmacay_user
DB_PASSWORD=your_secure_password
OPENAI_MODEL=gpt-5.5
DB_HOST=127.0.0.1
DB_USER=root
DB_PASSWORD=root
SMTP_HOST=smtp.example.org
SMTP_USER=relay
SMTP_PASSWORD=not-real
SEND_WEEKLY_REPORTS_ON_APR_CREATE=true
ALLOWED_ORIGINS=http://localhost:3000,https://yourdomain.com
"""


class E2EScriptTests(unittest.TestCase):
    def test_config_review_finds_the_problems(self):
        env = {'SECRET_KEY': 'your-secret-key-here-change-in-production', 'DB_USER': 'root', 'DB_PASSWORD': 'root',
               'SEND_WEEKLY_REPORTS_ON_APR_CREATE': 'true', 'ALLOWED_ORIGINS': 'https://yourdomain.com', 'FLASK_ENV': 'production',
               'SMTP_HOST': 'h', 'SMTP_USER': 'u', 'SMTP_PASSWORD': 'p'}
        text = ' | '.join(m for _, m in e2e_check.review_env(ENV_LIKE_YOURS, env))
        for expected in ('DB_HOST (lines 8, 12)', 'SECRET_KEY is a placeholder', 'as root', 'MYSQL_HOST', 'SEND_WEEKLY_REPORTS',
                         'ALLOWED_ORIGINS', 'AUTH_MODE is open', 'admin console is locked'):
            self.assertIn(expected, text)

    def test_posters_and_filing_into_a_copy(self):
        tmp = Path(tempfile.mkdtemp())
        e2e_check.OUT = tmp
        e2e_check.REPORT = {'checks': []}
        llm = FakeLLM([{'content': json.dumps(d)} for _, d in POSTERS[:4]])
        s = e2e_check.services_on_copy(e2e_check.memory_copy(None), llm)
        s.gov.set_setting('batch.parallel_reads', 1, 'test')
        imgs = []
        from PIL import Image
        for i in range(4):
            p = tmp / f'poster{i}.jpg'
            Image.new('RGB', (40, 60), (200, 160, 40)).save(p)
            imgs.append(str(p))
        plan = e2e_check.check_posters(s, imgs, do_file=True)
        self.assertEqual(len(plan['programs']), 2)                      # Nalanda Virasat (+ merged concert) and the circuit
        self.assertTrue((tmp / 'batch_plan.json').exists() and (tmp / 'posters_as_read.json').exists())
        self.assertTrue(list((tmp / 'apr_pdfs').glob('APR_*.pdf')))     # the circuit was ready and got filed
        self.assertFalse(list(tmp.glob('**/outbox/*.eml')) == [] and False)
        results = [c['result'] for c in e2e_check.REPORT['checks']]
        self.assertNotIn('FAIL', results)


if __name__ == '__main__':
    unittest.main()
