# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Flask Application Factory for SPIC MACAY Event Agent
"""
from flask import Flask, render_template
from flask_cors import CORS
import os
import logging
from logging.handlers import RotatingFileHandler

def create_app(config=None):
    """Create and configure Flask application"""
    
    app = Flask(__name__)
    
    # Load configuration
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'dev-secret-key-change-in-production')
    app.config['DEBUG'] = os.getenv('DEBUG', 'False').lower() == 'true'
    
    # Database configuration
    app.config['DB_CONFIG'] = {
        'pool_name': 'spicmacay_pool',
        'pool_size': 5,
        'host': os.getenv('DB_HOST', 'localhost'),
        'port': int(os.getenv('DB_PORT', 3306)),
        'user': os.getenv('DB_USER', 'root'),
        'password': os.getenv('DB_PASSWORD', ''),
        'database': os.getenv('DB_NAME', 'spicmacay'),
        'raise_on_warnings': True
    }
    
    # SMTP Configuration
    app.config['SMTP_CONFIG'] = {
        'host': os.getenv('SMTP_HOST', 'smtp.gmail.com'),
        'port': int(os.getenv('SMTP_PORT', 587)),
        'user': os.getenv('SMTP_USER', ''),
        'password': os.getenv('SMTP_PASSWORD', ''),
        'from_email': os.getenv('FROM_EMAIL', 'noreply@spicmacay.org')
    }
    
    # OpenAI Configuration
    app.config['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY', '')
    app.config['OPENAI_MODEL'] = os.getenv('OPENAI_MODEL', 'gpt-4-1106-preview')
    
    # Enable CORS
    CORS(app, origins=os.getenv('ALLOWED_ORIGINS', '*').split(','))
    
    # Setup logging
    setup_logging(app)
    
    # Register routes
    register_routes(app)
    
    # Register error handlers
    register_error_handlers(app)
    
    return app

def setup_logging(app):
    """Configure application logging"""
    
    if not os.path.exists('logs'):
        os.makedirs('logs')
    
    # File handler
    file_handler = RotatingFileHandler(
        'logs/spicmacay_app.log',
        maxBytes=10240000,  # 10MB
        backupCount=10
    )
    
    file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
    ))
    
    log_level = getattr(logging, os.getenv('LOG_LEVEL', 'INFO').upper())
    file_handler.setLevel(log_level)
    
    app.logger.addHandler(file_handler)
    app.logger.setLevel(log_level)
    app.logger.info('SPIC MACAY Event Agent startup')

def register_routes(app):
    """Register application routes"""
    
    # Import blueprints
    from app.routes.chat import chat_bp
    from app.routes.events import events_bp, init_services as init_event_services
    from app.routes.dashboard import dashboard_bp
    
    # Initialize services for events blueprint
    init_event_services(app)
    
    # Register blueprints
    app.register_blueprint(chat_bp, url_prefix='/api/chat')
    app.register_blueprint(events_bp, url_prefix='/api/events')
    app.register_blueprint(dashboard_bp, url_prefix='/api/dashboard')
    
    # Main route
    @app.route('/')
    def index():
        return render_template('index.html')
    
    # Dashboard route
    @app.route('/dashboard')
    def dashboard():
        return render_template('dashboard.html')

def register_error_handlers(app):
    """Register error handlers"""
    
    @app.errorhandler(404)
    def not_found_error(error):
        return {'error': 'Resource not found'}, 404
    
    @app.errorhandler(500)
    def internal_error(error):
        app.logger.error(f'Server Error: {error}')
        return {'error': 'Internal server error'}, 500
