# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Flask Application Factory for SPIC MACAY Event Agent
Integrated with Multi-Agent System
"""
from flask import Flask, render_template
from flask_cors import CORS
from werkzeug.middleware.proxy_fix import ProxyFix
import os
import logging
from logging.handlers import RotatingFileHandler
import traceback
from app.services.voice_service import VoiceService  # NEW


class SubPathFallbackMiddleware:
    """
    Makes the app aware it's mounted under a URL sub-path behind a reverse proxy —
    e.g. https://spicmacay.in/spicmacay_ai_agent/New_AI_Portal/ proxied through to this
    app running on its own port. Without this, url_for() (static assets, redirects)
    generates root-relative URLs like /static/js/chat.js, which 404 once a proxy prefix
    is involved, because the browser resolves them against the domain root instead of
    the proxied path.

    Only takes effect if SCRIPT_NAME hasn't already been set by ProxyFix from an
    X-Forwarded-Prefix header sent by the proxy — so a properly configured proxy always
    takes precedence, and this is purely a fallback for when it isn't (e.g. a plain
    path-stripping ProxyPass with no custom headers). Configure the sub-path via the
    URL_PREFIX env var, e.g. URL_PREFIX=/spicmacay_ai_agent/New_AI_Portal
    """
    def __init__(self, wsgi_app, fallback_prefix: str = ''):
        self.wsgi_app = wsgi_app
        self.fallback_prefix = fallback_prefix.rstrip('/')

    def __call__(self, environ, start_response):
        if self.fallback_prefix and not environ.get('SCRIPT_NAME'):
            environ['SCRIPT_NAME'] = self.fallback_prefix
        return self.wsgi_app(environ, start_response)


def create_app(config=None):
    """
    Create and configure Flask application with integrated agent system
    
    Initialization Flow:
    1. Create Flask app
    2. Load configuration
    3. Setup logging
    4. Initialize database connection
    5. Initialize services (Event, Notification)
    6. Initialize AI Agent System (Main entry point with routing)
    7. Register routes (including agent blueprints)
    8. Register error handlers
    """
    
    app = Flask(__name__)

    # ========================================
    # STEP 0: Reverse-proxy / sub-path awareness
    # ========================================
    # Behind a reverse proxy (e.g. https://spicmacay.in/spicmacay_ai_agent/New_AI_Portal/),
    # the app needs to know its own URL prefix, or url_for()-generated links (static assets,
    # redirects) come out root-relative and 404. ProxyFix picks this up automatically from
    # standard X-Forwarded-* headers when the proxy sends them; SubPathFallbackMiddleware
    # covers the common case where the proxy just strips the prefix and forwards the rest
    # with no special headers — set URL_PREFIX in the environment to match.
    app.wsgi_app = SubPathFallbackMiddleware(app.wsgi_app, fallback_prefix=os.getenv('URL_PREFIX', ''))
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1)

    # ========================================
    # STEP 1: Load Configuration
    # ========================================
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'dev-secret-key-change-in-production')
    app.config['DEBUG'] = os.getenv('DEBUG', 'False').lower() == 'true'
    
    # Database configuration
    app.config['DB_CONFIG'] = {
        'pool_name': 'spicmacay_pool',
        'pool_size': 5,
        'host': os.getenv('DB_HOST', 'localhost'),
        'port': int(os.getenv('DB_PORT', 3306)),
        'user': os.getenv('DB_USER', 'root'),
        'password': os.getenv('DB_PASSWORD', ''),
        'database': os.getenv('DB_NAME', 'spicmacay'),
        'raise_on_warnings': True
    }
    
    # SMTP Configuration
    _apr_cc_raw = os.getenv('APR_CC_RECIPIENTS', 'smhighereducation@spicmacay.com')
    _apr_cc_list = [e.strip() for e in _apr_cc_raw.split(',') if e.strip()]
    app.config['SMTP_CONFIG'] = {
        'host': os.getenv('SMTP_HOST', 'smtp.gmail.com'),
        'port': int(os.getenv('SMTP_PORT', 587)),
        'user': os.getenv('SMTP_USER', ''),
        'password': os.getenv('SMTP_PASSWORD', ''),
        'from_email': os.getenv('FROM_EMAIL', 'noreply@spicmacay.org'),
        'apr_cc_recipients': _apr_cc_list,   # list; add more in APR_CC_RECIPIENTS env var
        # SPIC MACAY's own collection bank account — what host institutions pay their program
        # contribution INTO (distinct from artist payout bank details). Defaults match the
        # sample Request for Payment documents; override per-chapter via env vars.
        'sm_bank_config': {
            'bank_name':      os.getenv('SM_BANK_NAME', 'State Bank of India'),
            'account_name':   os.getenv('SM_BANK_ACCOUNT_NAME', 'SPIC MACAY'),
            'account_number': os.getenv('SM_BANK_ACCOUNT_NO', '10773571902'),
            'ifsc_code':      os.getenv('SM_BANK_IFSC', 'SBIN0011781'),
        },
        # Optional feedback-form URL for payment reminder emails — left blank until the real
        # form link is provided; that line is simply omitted from the email if unset.
        'feedback_form_url': os.getenv('FEEDBACK_FORM_URL', ''),
    }

    # OpenAI Configuration
    app.config['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY', '')
    app.config['OPENAI_MODEL'] = os.getenv('OPENAI_MODEL', 'gpt-4o')
    
    # Validate OpenAI API key
    if not app.config['OPENAI_API_KEY']:
        raise ValueError("OPENAI_API_KEY environment variable is required")
    
    # Enable CORS
    CORS(app, origins=os.getenv('ALLOWED_ORIGINS', '*').split(','))
    
    # ========================================
    # STEP 2: Setup Logging
    # ========================================
    setup_logging(app)
    
    app.logger.info("=" * 60)
    app.logger.info("SPIC MACAY Event Agent System - Initialization")
    app.logger.info("=" * 60)
    
    # ========================================
    # STEP 3: Initialize Database Connection
    # ========================================
    app.logger.info("Initializing database connection...")
    from app.models.database import DatabaseManager
    from app.models.database import DatabaseValidator
        # Initialize services
    global db_manager, db_validator, event_service, notification_service, voice_service, agent
    
    try:
        db_manager = DatabaseManager(app.config['DB_CONFIG'])
        db_validator = DatabaseValidator(db_manager)
        app.db_manager = db_manager
        app.db_validator = db_validator
        
        app.logger.info("Database connected successfully")
    except Exception as e:
        app.logger.error(f"Database connection failed: {e}")
        app.logger.error(f"Full traceback: {traceback.format_exc()}")
        raise Exception("Failed to initialize database") from e
    
    # ========================================
    # STEP 4: Initialize Services
    # ========================================
    app.logger.info("Initializing application services...")
    
    # Event Service
    try:
        from app.services.event_service import EventService
        event_service = EventService(db_manager)
        app.event_service = event_service
        app.logger.info("  Event Service initialized")
    except Exception as e:
        app.logger.error(f"Event Service initialization failed: {e}")
        app.logger.error(f"Full traceback: {traceback.format_exc()}")
        raise Exception("Failed to initialize Event Service") from e
    
    app.notification_service = None
    notification_service = None
    
       # Voice Service (NEW)
    voice_service = VoiceService(app.config['OPENAI_API_KEY'])
    app.logger.info(" Voice service initialized (OpenAI Whisper + TTS)")
    
    # Notification Service
    try:
        from app.models.notifications import NotificationService
        notification_service = NotificationService(app.config['SMTP_CONFIG'])
        app.notification_service = notification_service
        app.logger.info("  Notification Service initialized")
    except Exception as e:
        app.logger.error(f"Notification Service initialization failed: {e}")
        app.logger.error(f"Full traceback: {traceback.format_exc()}")
        # Don't fail on notification service - it's not critical
        app.notification_service = None
        app.logger.warning("  Notification Service disabled due to initialization error")
    
    # ========================================
    # STEP 5: Initialize AI Agent System
    # ========================================
    app.logger.info("Initializing AI Agent System...")
    
    try:
        from app.models.main_agent import ConversationalAgent
        
        # Create the main agent (which initializes sub-agents internally)
        agent = ConversationalAgent(
            api_key=app.config['OPENAI_API_KEY'],
            db_manager=db_manager,
            db_validator=db_validator,
            event_service=event_service,
            notification_service=notification_service
        )
        
        # Store in app context - accessible via current_app.agent
        app.agent = agent
        
        app.logger.info("  SPIC MACAY Agent (Event Creation) - Ready")
        app.logger.info("  Workflow Agent (Information Queries) - Ready")
        app.logger.info("  Agent Router (Intelligent Routing) - Ready")
        app.logger.info("AI Agent System initialized successfully")
        
      
        # Schedule periodic cleanup of old voice files
        import atexit
        atexit.register(lambda: voice_service.cleanup_old_files(max_age_hours=24))        
        
    except Exception as e:
        app.logger.error(f"AI Agent System initialization failed: {e}")
        app.logger.error(f"Full traceback: {traceback.format_exc()}")
        raise Exception("Failed to initialize AI Agent System") from e
    
    # ========================================
    # STEP 5b: Initialize Knowledge (RAG) Agents  [Added by Claude]
    # ========================================
    # These are document-grounded agents (Convention Guide, Movement Programme
    # Guide) backed by your Google Drive folders. This block NEVER raises - if
    # anything is misconfigured, the agents simply report "no documents indexed"
    # and the rest of the app keeps working.
    app.knowledge_agents = {}
    try:
        from openai import OpenAI
        from app.services.drive_rag_service import DriveRagService
        from app.models.knowledge_agent import build_knowledge_agents

        rag_client = OpenAI(api_key=app.config['OPENAI_API_KEY'])
        rag_service = DriveRagService(
            openai_client=rag_client,
            embedding_model=os.getenv('EMBEDDING_MODEL', 'text-embedding-3-small'),
            index_dir=os.getenv('KNOWLEDGE_INDEX_DIR', 'knowledge_index'),
        )
        app.rag_service = rag_service
        app.knowledge_agents = build_knowledge_agents(
            api_key=app.config['OPENAI_API_KEY'],
            rag_service=rag_service,
            model=app.config['OPENAI_MODEL'],
        )
        app.logger.info(f"  Knowledge Agents ready: {list(app.knowledge_agents.keys())}")
    except Exception as e:
        app.logger.warning(f"Knowledge Agents not initialized ({e}). "
                           f"Convention/Movement guides will be unavailable until fixed.")

    # ========================================
    # STEP 6: Register Routes
    # ========================================
    app.logger.info("Registering application routes...")
    register_routes(app)
    app.logger.info("Routes registered successfully")
    
    # ========================================
    # STEP 7: Register Error Handlers
    # ========================================
    register_error_handlers(app)
    
    app.logger.info("=" * 60)
    app.logger.info("Application initialization complete!")
    app.logger.info("Available Components:")
    app.logger.info("  - Database Manager: app.db_manager")
    app.logger.info("  - Event Service: app.event_service")
    app.logger.info("  - Notification Service: app.notification_service")
    app.logger.info("  - AI Agent: app.agent")
    app.logger.info("=" * 60)
    
    return app


def setup_logging(app):
    """Configure application logging"""
    
    if not os.path.exists('logs'):
        os.makedirs('logs')
    
    # File handler
    file_handler = RotatingFileHandler(
        'logs/spicmacay_app.log',
        maxBytes=10240000,  # 10MB
        backupCount=10
    )
    
    file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
    ))
    
    log_level = getattr(logging, os.getenv('LOG_LEVEL', 'INFO').upper())
    file_handler.setLevel(log_level)
    
    app.logger.addHandler(file_handler)
    app.logger.setLevel(log_level)
    app.logger.info('SPIC MACAY Event Agent startup')


def register_routes(app):
    """
    Register application routes
    
    Blueprints:
    1. chat_bp - Original chat interface (legacy support)
    2. agent_bp - Unified agent API (new system with routing)
    3. events_bp - Event management
    4. dashboard_bp - Dashboard
    """
    
    # ========================================
    # Import Existing Blueprints
    # ========================================
    try:
        from app.routes.chat import chat_bp
        app.logger.info("  Chat blueprint imported")
    except ImportError as e:
        app.logger.warning(f"Chat blueprint not found: {e}")
        chat_bp = None
    
    try:
        from app.routes.events import events_bp, init_services as init_event_services
        app.logger.info("  Events blueprint imported")
    except ImportError as e:
        app.logger.warning(f"Events blueprint not found: {e}")
        events_bp = None
        init_event_services = None
    
    try:
        from app.routes.dashboard import dashboard_bp
        app.logger.info("  Dashboard blueprint imported")
    except ImportError as e:
        app.logger.warning(f"Dashboard blueprint not found: {e}")
        dashboard_bp = None
    
    # ========================================
    # Import New Agent Blueprints
    # ========================================
    try:
        from app.routes.convs import agent_bp
        app.logger.info("  Unified Agent API blueprint imported")
    except ImportError as e:
        app.logger.warning(f"Agent API blueprint not found: {e}")
        agent_bp = None
        

    from app.routes.voice_routes import voice_bp

    __all__ = ['main_bp', 'agent_bp', 'voice_bp']        
    
    # ========================================
    # Register Blueprints
    # ========================================
    
    # Original chat blueprint (legacy support)
    if chat_bp:
        app.register_blueprint(chat_bp, url_prefix='/api/chat')
        app.logger.info("  Registered: /api/chat (Legacy Chat)")
    
    # Unified agent API (new routing system)
    if agent_bp:
        app.register_blueprint(agent_bp, url_prefix='/api/agent')
        app.logger.info("  Registered: /api/agent (Unified Agent API)")
    
    # Events blueprint
    if events_bp:
        if init_event_services:
            init_event_services(app)
        app.register_blueprint(events_bp, url_prefix='/api/events')
        app.logger.info("  Registered: /api/events (Event Management)")
    
    # Dashboard blueprint
    if dashboard_bp:
        app.register_blueprint(dashboard_bp, url_prefix='/api/dashboard')
        app.logger.info("  Registered: /api/dashboard (Dashboard)")
        
        app.logger.info("  Registered: /api/agent (Unified Agent API)")
    
    # Events blueprint
    if voice_bp:
        if init_event_services:
            init_event_services(app)
        app.register_blueprint(voice_bp, url_prefix='/api/voice')
        app.logger.info("  Registered: /api/voice (Voice)")        

    # Knowledge (RAG) agents blueprint  [Added by Claude]
    try:
        from app.routes.knowledge import knowledge_bp
        app.register_blueprint(knowledge_bp, url_prefix='/api/knowledge')
        app.logger.info("  Registered: /api/knowledge (Convention & Movement Guides)")
    except ImportError as e:
        app.logger.warning(f"Knowledge blueprint not found: {e}")
    
    # ========================================
    # Main Application Routes
    # ========================================
    
    @app.route('/')
    def index():
        """Landing page with cards for each agent  [Added by Claude]"""
        return render_template('index.html')

    @app.route('/assistant')
    def assistant():
        """Original event/voice assistant chat  [Added by Claude]"""
        return render_template('assistant.html')

    @app.route('/guide/<agent_key>')
    def guide(agent_key):
        """Interactive document-grounded guide (convention / movement)  [Added by Claude]"""
        from app.models.knowledge_agent import KNOWLEDGE_AGENTS
        cfg = KNOWLEDGE_AGENTS.get(agent_key)
        if not cfg:
            return render_template('index.html'), 404
        # If you own a licensed photo, drop it at static/img/<key>_guide.(jpg|png)
        # and it will be used in place of the generic illustration.
        guide_photo = None
        for ext in ('jpg', 'jpeg', 'png', 'webp'):
            rel = f"img/{agent_key}_guide.{ext}"
            if os.path.exists(os.path.join(app.static_folder, rel)):
                guide_photo = rel
                break
        return render_template('knowledge_chat.html', agent=cfg, guide_photo=guide_photo)
    
    @app.route('/dashboard')
    def dashboard():
        """Dashboard interface"""
        return render_template('dashboard.html')
    
    @app.route('/health')
    def health_check():
        """Health check endpoint"""
        return {
            'status': 'healthy',
            'agent_initialized': hasattr(app, 'agent'),
            'db_connected': hasattr(app, 'db_manager'),
            'services': {
                'event_service': hasattr(app, 'event_service'),
                'notification_service': hasattr(app, 'notification_service')
            }
        }
    
    app.logger.info("  Registered: / (Main Interface)")
    app.logger.info("  Registered: /dashboard (Dashboard Interface)")
    app.logger.info("  Registered: /health (Health Check)")
    
    # ========================================
    # API Documentation Route
    # ========================================
    #,
            # 'System': {
            #    'GET /api/agent/health': 'Health check',
            #    'GET /api': 'API documentation (this page)'
            #}
    
    @app.route('/api')
    def api_documentation():
        """API documentation"""
        endpoints = {
            'Unified Agent API': {
                'POST /api/agent/chat': 'Send message to agent (auto-routed)',
                'POST /api/agent/start': 'Start new conversation',
                'POST /api/agent/reset': 'Reset conversation',
                'GET /api/agent/history': 'Get conversation history',
                'GET /api/agent/status': 'Get agent system status'
            },
            'Legacy Chat API': {
                'POST /api/chat/start': 'Start chat (legacy)',
                'POST /api/chat/message': 'Send message (legacy)',
                'POST /api/chat/reset': 'Reset chat (legacy)',
                'GET /api/chat/history': 'Get history (legacy)'
            },
            'Event Management': {
                'GET /api/events': 'List all events',
                'POST /api/events': 'Create new event',
                'GET /api/events/<id>': 'Get event details',
                'PUT /api/events/<id>': 'Update event',
                'DELETE /api/events/<id>': 'Delete event'
            },
            'Dashboard': {
                'GET /api/dashboard/stats': 'Get dashboard statistics',
                'GET /api/dashboard/recent-events': 'Get recent events'
            }
        }
        
        return {
            'message': 'SPIC MACAY Event Agent API',
            'version': '2.0',
            'endpoints': endpoints,
            'agent_system': {
                'spic_macay_agent': 'Handles event creation and APR management',
                'workflow_agent': 'Handles information queries with multi-stage processing',
                'agent_router': 'Intelligently routes queries to appropriate agent'
            }
        }
    
    app.logger.info("  Registered: /api (API Documentation)")

# Code Generated by Sidekick is for learning and experimentation purposes only.
def register_error_handlers(app):
    """Register error handlers"""
    
    @app.errorhandler(404)
    def not_found_error(error):
        from flask import request
        
        # Ignore Chrome DevTools and browser-specific requests
        ignored_paths = [
            '/.well-known/',
            '/favicon.ico',
            '/apple-touch-icon',
            '/robots.txt',
            '/sitemap.xml'
        ]
        
        # Check if this is an ignorable path
        if any(request.path.startswith(path) for path in ignored_paths):
            # Don't log these - they're just browser noise
            return {'error': 'Not found'}, 404
        
        # Log actual 404 errors
        app.logger.warning(f"404 Error - URL: {request.url}")
        app.logger.warning(f"404 Error - Method: {request.method}")
        app.logger.warning(f"404 Error - Path: {request.path}")
        app.logger.warning(f"404 Error - Endpoint: {request.endpoint}")
        
        return {
            'error': 'Resource not found',
            'path': request.path,
            'method': request.method
        }, 404
    
    @app.errorhandler(500)
    def internal_error(error):
        app.logger.error(f'Server Error: {error}')
        app.logger.error(f'Full traceback: {traceback.format_exc()}')
        return {'error': 'Internal server error'}, 500
    
    @app.errorhandler(Exception)
    def handle_exception(error):
        """Catch-all exception handler"""
        app.logger.error(f'Unhandled Exception: {error}')
        app.logger.error(f'Error type: {type(error).__name__}')
        app.logger.error(f'Full traceback: {traceback.format_exc()}')
        
        return {
            'error': 'An unexpected error occurred',
            'message': str(error) if app.config['DEBUG'] else 'Please contact support'
        }, 500
