# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Flask Application Factory for SPIC MACAY Event Agent
Integrated with Multi-Agent System
"""
from flask import Flask, render_template
from flask_cors import CORS
import os
import logging
from logging.handlers import RotatingFileHandler
import traceback


def create_app(config=None):
    """
    Create and configure Flask application with integrated agent system
    
    Initialization Flow:
    1. Create Flask app
    2. Load configuration
    3. Setup logging
    4. Initialize database connection
    5. Initialize services (Event, Notification)
    6. Initialize AI Agent System (Main entry point with routing)
    7. Register routes (including agent blueprints)
    8. Register error handlers
    """
    
    app = Flask(__name__)
    
    # ========================================
    # STEP 1: Load Configuration
    # ========================================
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'dev-secret-key-change-in-production')
    app.config['DEBUG'] = os.getenv('DEBUG', 'False').lower() == 'true'
    
    # Database configuration
    app.config['DB_CONFIG'] = {
        'pool_name': 'spicmacay_pool',
        'pool_size': 5,
        'host': os.getenv('DB_HOST', 'localhost'),
        'port': int(os.getenv('DB_PORT', 3306)),
        'user': os.getenv('DB_USER', 'root'),
        'password': os.getenv('DB_PASSWORD', ''),
        'database': os.getenv('DB_NAME', 'spicmacay'),
        'raise_on_warnings': True
    }
    
    # SMTP Configuration
    app.config['SMTP_CONFIG'] = {
        'host': os.getenv('SMTP_HOST', 'smtp.gmail.com'),
        'port': int(os.getenv('SMTP_PORT', 587)),
        'user': os.getenv('SMTP_USER', ''),
        'password': os.getenv('SMTP_PASSWORD', ''),
        'from_email': os.getenv('FROM_EMAIL', 'noreply@spicmacay.org')
    }
    
    # OpenAI Configuration
    app.config['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY', '')
    app.config['OPENAI_MODEL'] = os.getenv('OPENAI_MODEL', 'gpt-4o')
    
    # Validate OpenAI API key
    if not app.config['OPENAI_API_KEY']:
        raise ValueError("OPENAI_API_KEY environment variable is required")
    
    # Enable CORS
    CORS(app, origins=os.getenv('ALLOWED_ORIGINS', '*').split(','))
    
    # ========================================
    # STEP 2: Setup Logging
    # ========================================
    setup_logging(app)
    
    app.logger.info("=" * 60)
    app.logger.info("SPIC MACAY Event Agent System - Initialization")
    app.logger.info("=" * 60)
    
    # ========================================
    # STEP 3: Initialize Database Connection
    # ========================================
    app.logger.info("Initializing database connection...")
    from app.models.database import DatabaseManager
    from app.models.database import DatabaseValidator
    
    try:
        db_manager = DatabaseManager(app.config['DB_CONFIG'])
        db_validator = DatabaseValidator(db_manager)
        app.db_manager = db_manager
        app.db_validator = db_validator
        
        app.logger.info("Database connected successfully")
    except Exception as e:
        app.logger.error(f"Database connection failed: {e}")
        app.logger.error(f"Full traceback: {traceback.format_exc()}")
        raise Exception("Failed to initialize database") from e
    
    # ========================================
    # STEP 4: Initialize Services
    # ========================================
    app.logger.info("Initializing application services...")
    
    # Event Service
    try:
        from app.services.event_service import EventService
        event_service = EventService(db_manager)
        app.event_service = event_service
        app.logger.info("  Event Service initialized")
    except Exception as e:
        app.logger.error(f"Event Service initialization failed: {e}")
        app.logger.error(f"Full traceback: {traceback.format_exc()}")
        raise Exception("Failed to initialize Event Service") from e
    
    app.notification_service = None
    notification_service = None
    # Notification Service
    #try:
    #    from app.services.notification_service import NotificationService
    #    notification_service = NotificationService(app.config['SMTP_CONFIG'])
    #    app.notification_service = notification_service
    #    app.logger.info("  Notification Service initialized")
    #except Exception as e:
    #    app.logger.error(f"Notification Service initialization failed: {e}")
    #    app.logger.error(f"Full traceback: {traceback.format_exc()}")
    #    # Don't fail on notification service - it's not critical
    #    app.notification_service = None
    #    app.logger.warning("  Notification Service disabled due to initialization error")
    
    # ========================================
    # STEP 5: Initialize AI Agent System
    # ========================================
    app.logger.info("Initializing AI Agent System...")
    
    try:
        from app.models.main_agent import ConversationalAgent
        
        # Create the main agent (which initializes sub-agents internally)
        agent = ConversationalAgent(
            api_key=app.config['OPENAI_API_KEY'],
            db_manager=db_manager,
            db_validator=db_validator,
            event_service=event_service,
            notification_service=notification_service
        )
        
        # Store in app context - accessible via current_app.agent
        app.agent = agent
        
        app.logger.info("  SPIC MACAY Agent (Event Creation) - Ready")
        app.logger.info("  Workflow Agent (Information Queries) - Ready")
        app.logger.info("  Agent Router (Intelligent Routing) - Ready")
        app.logger.info("AI Agent System initialized successfully")
        
    except Exception as e:
        app.logger.error(f"AI Agent System initialization failed: {e}")
        app.logger.error(f"Full traceback: {traceback.format_exc()}")
        raise Exception("Failed to initialize AI Agent System") from e
    
    # ========================================
    # STEP 6: Register Routes
    # ========================================
    app.logger.info("Registering application routes...")
    register_routes(app)
    app.logger.info("Routes registered successfully")
    
    # ========================================
    # STEP 7: Register Error Handlers
    # ========================================
    register_error_handlers(app)
    
    app.logger.info("=" * 60)
    app.logger.info("Application initialization complete!")
    app.logger.info("Available Components:")
    app.logger.info("  - Database Manager: app.db_manager")
    app.logger.info("  - Event Service: app.event_service")
    app.logger.info("  - Notification Service: app.notification_service")
    app.logger.info("  - AI Agent: app.agent")
    app.logger.info("=" * 60)
    
    return app


def setup_logging(app):
    """Configure application logging"""
    
    if not os.path.exists('logs'):
        os.makedirs('logs')
    
    # File handler
    file_handler = RotatingFileHandler(
        'logs/spicmacay_app.log',
        maxBytes=10240000,  # 10MB
        backupCount=10
    )
    
    file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
    ))
    
    log_level = getattr(logging, os.getenv('LOG_LEVEL', 'INFO').upper())
    file_handler.setLevel(log_level)
    
    app.logger.addHandler(file_handler)
    app.logger.setLevel(log_level)
    app.logger.info('SPIC MACAY Event Agent startup')


def register_routes(app):
    """
    Register application routes
    
    Blueprints:
    1. chat_bp - Original chat interface (legacy support)
    2. agent_bp - Unified agent API (new system with routing)
    3. events_bp - Event management
    4. dashboard_bp - Dashboard
    """
    
    # ========================================
    # Import Existing Blueprints
    # ========================================
    try:
        from app.routes.chat import chat_bp
        app.logger.info("  Chat blueprint imported")
    except ImportError as e:
        app.logger.warning(f"Chat blueprint not found: {e}")
        chat_bp = None
    
    try:
        from app.routes.events import events_bp, init_services as init_event_services
        app.logger.info("  Events blueprint imported")
    except ImportError as e:
        app.logger.warning(f"Events blueprint not found: {e}")
        events_bp = None
        init_event_services = None
    
    try:
        from app.routes.dashboard import dashboard_bp
        app.logger.info("  Dashboard blueprint imported")
    except ImportError as e:
        app.logger.warning(f"Dashboard blueprint not found: {e}")
        dashboard_bp = None
    
    # ========================================
    # Import New Agent Blueprints
    # ========================================
    try:
        from app.routes.convs import agent_bp
        app.logger.info("  Unified Agent API blueprint imported")
    except ImportError as e:
        app.logger.warning(f"Agent API blueprint not found: {e}")
        agent_bp = None
    
    # ========================================
    # Register Blueprints
    # ========================================
    
    # Original chat blueprint (legacy support)
    if chat_bp:
        app.register_blueprint(chat_bp, url_prefix='/api/chat')
        app.logger.info("  Registered: /api/chat (Legacy Chat)")
    
    # Unified agent API (new routing system)
    if agent_bp:
        app.register_blueprint(agent_bp, url_prefix='/api/agent')
        app.logger.info("  Registered: /api/agent (Unified Agent API)")
    
    # Events blueprint
    if events_bp:
        if init_event_services:
            init_event_services(app)
        app.register_blueprint(events_bp, url_prefix='/api/events')
        app.logger.info("  Registered: /api/events (Event Management)")
    
    # Dashboard blueprint
    if dashboard_bp:
        app.register_blueprint(dashboard_bp, url_prefix='/api/dashboard')
        app.logger.info("  Registered: /api/dashboard (Dashboard)")
    
    # ========================================
    # Main Application Routes
    # ========================================
    
    @app.route('/')
    def index():
        """Main interface"""
        return render_template('index.html')
    
    @app.route('/dashboard')
    def dashboard():
        """Dashboard interface"""
        return render_template('dashboard.html')
    
    @app.route('/health')
    def health_check():
        """Health check endpoint"""
        return {
            'status': 'healthy',
            'agent_initialized': hasattr(app, 'agent'),
            'db_connected': hasattr(app, 'db_manager'),
            'services': {
                'event_service': hasattr(app, 'event_service'),
                'notification_service': hasattr(app, 'notification_service')
            }
        }
    
    app.logger.info("  Registered: / (Main Interface)")
    app.logger.info("  Registered: /dashboard (Dashboard Interface)")
    app.logger.info("  Registered: /health (Health Check)")
    
    # ========================================
    # API Documentation Route
    # ========================================
    #,
            # 'System': {
            #    'GET /api/agent/health': 'Health check',
            #    'GET /api': 'API documentation (this page)'
            #}
    
    @app.route('/api')
    def api_documentation():
        """API documentation"""
        endpoints = {
            'Unified Agent API': {
                'POST /api/agent/chat': 'Send message to agent (auto-routed)',
                'POST /api/agent/start': 'Start new conversation',
                'POST /api/agent/reset': 'Reset conversation',
                'GET /api/agent/history': 'Get conversation history',
                'GET /api/agent/status': 'Get agent system status'
            },
            'Legacy Chat API': {
                'POST /api/chat/start': 'Start chat (legacy)',
                'POST /api/chat/message': 'Send message (legacy)',
                'POST /api/chat/reset': 'Reset chat (legacy)',
                'GET /api/chat/history': 'Get history (legacy)'
            },
            'Event Management': {
                'GET /api/events': 'List all events',
                'POST /api/events': 'Create new event',
                'GET /api/events/<id>': 'Get event details',
                'PUT /api/events/<id>': 'Update event',
                'DELETE /api/events/<id>': 'Delete event'
            },
            'Dashboard': {
                'GET /api/dashboard/stats': 'Get dashboard statistics',
                'GET /api/dashboard/recent-events': 'Get recent events'
            }
        }
        
        return {
            'message': 'SPIC MACAY Event Agent API',
            'version': '2.0',
            'endpoints': endpoints,
            'agent_system': {
                'spic_macay_agent': 'Handles event creation and APR management',
                'workflow_agent': 'Handles information queries with multi-stage processing',
                'agent_router': 'Intelligently routes queries to appropriate agent'
            }
        }
    
    app.logger.info("  Registered: /api (API Documentation)")

# Code Generated by Sidekick is for learning and experimentation purposes only.
def register_error_handlers(app):
    """Register error handlers"""
    
    @app.errorhandler(404)
    def not_found_error(error):
        from flask import request
        
        # Ignore Chrome DevTools and browser-specific requests
        ignored_paths = [
            '/.well-known/',
            '/favicon.ico',
            '/apple-touch-icon',
            '/robots.txt',
            '/sitemap.xml'
        ]
        
        # Check if this is an ignorable path
        if any(request.path.startswith(path) for path in ignored_paths):
            # Don't log these - they're just browser noise
            return {'error': 'Not found'}, 404
        
        # Log actual 404 errors
        app.logger.warning(f"404 Error - URL: {request.url}")
        app.logger.warning(f"404 Error - Method: {request.method}")
        app.logger.warning(f"404 Error - Path: {request.path}")
        app.logger.warning(f"404 Error - Endpoint: {request.endpoint}")
        
        return {
            'error': 'Resource not found',
            'path': request.path,
            'method': request.method
        }, 404
    
    @app.errorhandler(500)
    def internal_error(error):
        app.logger.error(f'Server Error: {error}')
        app.logger.error(f'Full traceback: {traceback.format_exc()}')
        return {'error': 'Internal server error'}, 500
    
    @app.errorhandler(Exception)
    def handle_exception(error):
        """Catch-all exception handler"""
        app.logger.error(f'Unhandled Exception: {error}')
        app.logger.error(f'Error type: {type(error).__name__}')
        app.logger.error(f'Full traceback: {traceback.format_exc()}')
        
        return {
            'error': 'An unexpected error occurred',
            'message': str(error) if app.config['DEBUG'] else 'Please contact support'
        }, 500
