# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Chat routes - Updated to use unified agent system
"""
from flask import Blueprint, request, jsonify, current_app
import logging

logger = logging.getLogger(__name__)

chat_bp = Blueprint('chat', __name__)


@chat_bp.route('/start', methods=['POST'])
def start_chat():
    """Start a new conversation"""
    try:
        agent = current_app.agent
        response = agent.start_conversation()
        return jsonify(response)
        
    except Exception as e:
        logger.error(f"Error starting chat: {e}", exc_info=True)
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@chat_bp.route('/message', methods=['POST'])
def send_message():
    """Send a message to the agent"""
    try:
        data = request.get_json()
        user_message = data.get('message', '')
        
        if not user_message:
            return jsonify({
                'success': False,
                'error': 'Message is required'
            }), 400
        
        agent = current_app.agent
        response = agent.process_message(user_message)
        
        return jsonify(response)
        
    except Exception as e:
        logger.error(f"Error processing message: {e}", exc_info=True)
        return jsonify({
            'success': False,
            'error': str(e),
            'response': 'I encountered an error. Please try again.'
        }), 500


@chat_bp.route('/reset', methods=['POST'])
def reset_chat():
    """Reset conversation"""
    try:
        agent = current_app.agent
        agent.reset_conversation()
        
        return jsonify({
            'success': True,
            'message': 'Conversation reset'
        })
        
    except Exception as e:
        logger.error(f"Error resetting chat: {e}", exc_info=True)
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@chat_bp.route('/history', methods=['GET'])
def get_history():
    """Get conversation history"""
    try:
        agent = current_app.agent
        history = agent.get_conversation_history()
        
        return jsonify({
            'success': True,
            'history': history
        })
        
    except Exception as e:
        logger.error(f"Error getting history: {e}", exc_info=True)
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500
