# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Unified Agent API Routes
Handles both SPIC MACAY event creation and information workflow queries
"""
from flask import Blueprint, request, jsonify, current_app, send_file
import logging
import traceback
import os

logger = logging.getLogger(__name__)

# Create blueprint for unified agent API
agent_bp = Blueprint('agent', __name__)


@agent_bp.route('/health', methods=['GET'])
def health_check():
    """Check agent system health"""
    try:
        agent = current_app.agent
        
        return jsonify({
            'status': 'healthy',
            'agents': {
                'conversational_agent': 'active',
                'spic_macay_agent': 'ready',
                'workflow_agent': 'ready',
                'router': 'active'
            },
            'context': getattr(agent, 'conversation_context', {})
        })
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return jsonify({
            'status': 'unhealthy',
            'error': str(e)
        }), 500


@agent_bp.route('/chat', methods=['POST'])
def chat():
    """
    Main chat endpoint - Unified entry point.
    Accepts JSON (text only) or multipart/form-data (image + optional text).
    """
    try:
        if not hasattr(current_app, 'agent'):
            return jsonify({'success': False, 'error': 'Agent system not initialized'}), 500

        agent = current_app.agent

        # ── Poster image upload (multipart/form-data) ────────────────────────
        content_type = request.content_type or ''
        if 'multipart/form-data' in content_type:
            import base64
            user_message = (request.form.get('message') or '').strip()
            image_file = request.files.get('image')
            if not image_file:
                return jsonify({'success': False, 'error': 'No image file in upload'}), 400

            img_bytes = image_file.read()
            if len(img_bytes) > 10 * 1024 * 1024:
                return jsonify({'success': False, 'error': 'Image too large — max 10 MB'}), 413

            image_b64 = base64.b64encode(img_bytes).decode('utf-8')
            mime_type  = image_file.content_type or 'image/jpeg'
            logger.info(f"Poster upload: {mime_type}, {len(img_bytes)//1024} KB")

            response = agent.process_message_with_image(user_message, image_b64, mime_type)
            logger.info(f"Poster response from {response.get('agent_type', 'unknown')} agent")
            return jsonify(response)

        # ── Normal JSON path ─────────────────────────────────────────────────
        data = request.get_json()

        if not data:
            logger.error("No JSON data received")
            return jsonify({
                'success': False,
                'error': 'No data provided'
            }), 400

        user_message = data.get('message', '')
        event_photos = data.get('event_photos')

        if not user_message and not event_photos:
            logger.error("Empty message received")
            return jsonify({
                'success': False,
                'error': 'Message is required'
            }), 400

        # Optional program/event photos (base64) — stashed until the program is created
        if event_photos:
            logger.info(f"Attaching {len(event_photos)} event photo(s) to conversation")
            agent.attach_pending_photos(event_photos)

        logger.info(f"Processing message: {user_message[:60]}...")
        response = agent.process_message(user_message)
        logger.info(f"Response generated by {response.get('agent_type', 'unknown')} agent")
        return jsonify(response)
        
    except KeyError as e:
        logger.error(f"KeyError in chat endpoint: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': f'Missing key: {str(e)}',
            'response': 'I encountered an error. Please try again or start a new conversation.'
        }), 500
        
    except Exception as e:
        logger.error(f"Error in chat endpoint: {e}")
        logger.error(f"Error type: {type(e).__name__}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e),
            'response': 'I encountered an error. Please try again.'
        }), 500


@agent_bp.route('/start', methods=['POST'])
def start_conversation():
    """
    Start a new conversation
    Initializes conversation state and returns greeting
    """
    try:
        if not hasattr(current_app, 'agent'):
            logger.error("Agent not found in application context")
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        
        logger.info("Starting new conversation...")
        
        # Start new conversation
        response = agent.start_conversation()
        
        logger.info("New conversation started successfully")
        
        return jsonify(response)
        
    except Exception as e:
        logger.error(f"Error starting conversation: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e),
            'response': 'Failed to start conversation. Please try again.'
        }), 500


@agent_bp.route('/reset', methods=['POST'])
def reset_conversation():
    """
    Reset conversation state
    Clears all conversation history and context
    """
    try:
        if not hasattr(current_app, 'agent'):
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        agent.reset_conversation()
        
        logger.info("Conversation reset successfully")
        
        return jsonify({
            'success': True,
            'message': 'Conversation reset successfully'
        })
        
    except Exception as e:
        logger.error(f"Error resetting conversation: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@agent_bp.route('/history', methods=['GET'])
def get_history():
    """
    Get conversation history
    Returns history from the currently active agent
    """
    try:
        if not hasattr(current_app, 'agent'):
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        history = agent.get_conversation_history()
        
        return jsonify({
            'success': True,
            'history': history
        })
        
    except Exception as e:
        logger.error(f"Error getting history: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@agent_bp.route('/apr/download/<path:request_id>', methods=['GET'])
def download_apr_pdf(request_id):
    """Serve a generated APR PDF for download."""
    try:
        from app.services.pdf_service import PDFS_DIR
        safe_id = request_id.replace('/', '_').replace('\\', '_')
        pdf_path = os.path.join(PDFS_DIR, f'{safe_id}.pdf')
        if not os.path.isfile(pdf_path):
            return jsonify({'success': False, 'error': 'PDF not found'}), 404
        return send_file(
            pdf_path,
            mimetype='application/pdf',
            as_attachment=True,
            download_name=f'APR_{safe_id}.pdf',
        )
    except Exception as e:
        logger.error(f"Error serving APR PDF: {e}")
        return jsonify({'success': False, 'error': str(e)}), 500


@agent_bp.route('/status', methods=['GET'])
def agent_status():
    """
    Get detailed status of all agents in the system
    Useful for monitoring and debugging
    """
    try:
        if not hasattr(current_app, 'agent'):
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        
        status = {
            'success': True,
            'system': {
                'main_agent': 'ConversationalAgent',
                'status': 'active'
            },
            'sub_agents': {
                'spic_macay_agent': {
                    'name': 'SPIC MACAY Event Agent',
                    'purpose': 'Event creation and APR management',
                    'status': 'ready'
                },
                'workflow_agent': {
                    'name': 'Information Workflow Agent',
                    'purpose': 'Multi-stage information queries',
                    'status': 'ready'
                },
                'router': {
                    'name': 'Agent Router',
                    'purpose': 'Intelligent query routing',
                    'status': 'active'
                }
            },
            'context': getattr(agent, 'conversation_context', {}),
            'current_agent': agent.conversation_context.get('agent_type', 'none')
        }
        
        return jsonify(status)
        
    except Exception as e:
        logger.error(f"Error getting agent status: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500
