# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Unified Agent API Routes
Handles both SPIC MACAY event creation and information workflow queries
"""
from flask import Blueprint, request, jsonify, current_app
import logging
import traceback

logger = logging.getLogger(__name__)

# Create blueprint for unified agent API
agent_bp = Blueprint('agent', __name__)


@agent_bp.route('/health', methods=['GET'])
def health_check():
    """Check agent system health"""
    try:
        agent = current_app.agent
        
        return jsonify({
            'status': 'healthy',
            'agents': {
                'conversational_agent': 'active',
                'spic_macay_agent': 'ready',
                'workflow_agent': 'ready',
                'router': 'active'
            },
            'context': getattr(agent, 'conversation_context', {})
        })
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return jsonify({
            'status': 'unhealthy',
            'error': str(e)
        }), 500


@agent_bp.route('/chat', methods=['POST'])
def chat():
    """
    Main chat endpoint - Unified entry point
    Automatically routes to appropriate agent based on query intent
    """
    try:
        # Get request data
        data = request.get_json()
        
        if not data:
            logger.error("No JSON data received")
            return jsonify({
                'success': False,
                'error': 'No data provided'
            }), 400
        
        user_message = data.get('message', '')
        
        if not user_message:
            logger.error("Empty message received")
            return jsonify({
                'success': False,
                'error': 'Message is required'
            }), 400
        
        # Get agent from app context
        if not hasattr(current_app, 'agent'):
            logger.error("Agent not found in application context")
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        
        logger.info(f"Processing message: {user_message[:60]}...")
        
        # Process message through the unified agent system
        # Router will automatically determine which agent to use
        response = agent.process_message(user_message)
        
        logger.info(f"Response generated by {response.get('agent_type', 'unknown')} agent")
        
        return jsonify(response)
        
    except KeyError as e:
        logger.error(f"KeyError in chat endpoint: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': f'Missing key: {str(e)}',
            'response': 'I encountered an error. Please try again or start a new conversation.'
        }), 500
        
    except Exception as e:
        logger.error(f"Error in chat endpoint: {e}")
        logger.error(f"Error type: {type(e).__name__}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e),
            'response': 'I encountered an error. Please try again.'
        }), 500


@agent_bp.route('/start', methods=['POST'])
def start_conversation():
    """
    Start a new conversation
    Initializes conversation state and returns greeting
    """
    try:
        if not hasattr(current_app, 'agent'):
            logger.error("Agent not found in application context")
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        
        logger.info("Starting new conversation...")
        
        # Start new conversation
        response = agent.start_conversation()
        
        logger.info("New conversation started successfully")
        
        return jsonify(response)
        
    except Exception as e:
        logger.error(f"Error starting conversation: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e),
            'response': 'Failed to start conversation. Please try again.'
        }), 500


@agent_bp.route('/reset', methods=['POST'])
def reset_conversation():
    """
    Reset conversation state
    Clears all conversation history and context
    """
    try:
        if not hasattr(current_app, 'agent'):
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        agent.reset_conversation()
        
        logger.info("Conversation reset successfully")
        
        return jsonify({
            'success': True,
            'message': 'Conversation reset successfully'
        })
        
    except Exception as e:
        logger.error(f"Error resetting conversation: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@agent_bp.route('/history', methods=['GET'])
def get_history():
    """
    Get conversation history
    Returns history from the currently active agent
    """
    try:
        if not hasattr(current_app, 'agent'):
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        history = agent.get_conversation_history()
        
        return jsonify({
            'success': True,
            'history': history
        })
        
    except Exception as e:
        logger.error(f"Error getting history: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@agent_bp.route('/status', methods=['GET'])
def agent_status():
    """
    Get detailed status of all agents in the system
    Useful for monitoring and debugging
    """
    try:
        if not hasattr(current_app, 'agent'):
            return jsonify({
                'success': False,
                'error': 'Agent system not initialized'
            }), 500
        
        agent = current_app.agent
        
        status = {
            'success': True,
            'system': {
                'main_agent': 'ConversationalAgent',
                'status': 'active'
            },
            'sub_agents': {
                'spic_macay_agent': {
                    'name': 'SPIC MACAY Event Agent',
                    'purpose': 'Event creation and APR management',
                    'status': 'ready'
                },
                'workflow_agent': {
                    'name': 'Information Workflow Agent',
                    'purpose': 'Multi-stage information queries',
                    'status': 'ready'
                },
                'router': {
                    'name': 'Agent Router',
                    'purpose': 'Intelligent query routing',
                    'status': 'active'
                }
            },
            'context': getattr(agent, 'conversation_context', {}),
            'current_agent': agent.conversation_context.get('agent_type', 'none')
        }
        
        return jsonify(status)
        
    except Exception as e:
        logger.error(f"Error getting agent status: {e}")
        logger.error(f"Full traceback: {traceback.format_exc()}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500
