# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Dashboard API Routes
"""
from flask import Blueprint, jsonify, current_app
from app.models.database import DatabaseManager
from app.services.event_service import EventService
import logging

logger = logging.getLogger(__name__)

dashboard_bp = Blueprint('dashboard', __name__)

# Services
db_manager = None
event_service = None

def init_services(app):
    """Initialize services"""
    global db_manager, event_service
    
    db_manager = DatabaseManager(app.config['DB_CONFIG'])
    event_service = EventService(db_manager)

@dashboard_bp.route('/stats', methods=['GET'])
def get_stats():
    """Get dashboard statistics"""
    try:
        stats = event_service.get_dashboard_stats()
        
        return jsonify({
            'success': True,
            'stats': stats
        })
        
    except Exception as e:
        logger.error(f"Error fetching dashboard stats: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500
