# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Event Management API Routes
"""
from flask import Blueprint, request, jsonify, current_app
from app.models.database import DatabaseManager
from app.services.event_service import EventService
import logging

logger = logging.getLogger(__name__)

events_bp = Blueprint('events', __name__)

# Global service instances
db_manager = None
event_service = None

def init_services(app):
    """Initialize service instances with app config"""
    global db_manager, event_service
    db_manager = DatabaseManager(app.config['DB_CONFIG'])
    event_service = EventService(db_manager)

@events_bp.route('/list', methods=['GET'])
def list_events():
    """Get list of events with optional filters"""
    try:
        # Get query parameters
        filters = {
            'start_date': request.args.get('start_date'),
            'end_date': request.args.get('end_date'),
            'state': request.args.get('state'),
            'chapter': request.args.get('chapter'),
            'status': request.args.get('status'),
            'limit': int(request.args.get('limit', 50)),
            'offset': int(request.args.get('offset', 0))
        }
        
        # Remove None values
        filters = {k: v for k, v in filters.items() if v is not None}
        
        events = event_service.get_events(filters)
        
        return jsonify({
            'success': True,
            'events': events,
            'count': len(events)
        })
        
    except Exception as e:
        logger.error(f"Error listing events: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@events_bp.route('/<int:event_id>', methods=['GET'])
def get_event(event_id):
    """Get single event by ID"""
    try:
        event = event_service.get_event_by_id(event_id)
        
        if not event:
            return jsonify({
                'success': False,
                'error': 'Event not found'
            }), 404
        
        return jsonify({
            'success': True,
            'event': event
        })
        
    except Exception as e:
        logger.error(f"Error fetching event: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@events_bp.route('/create', methods=['POST'])
def create_event():
    """Create new event"""
    try:
        event_data = request.json
        
        if not event_data:
            return jsonify({
                'success': False,
                'error': 'No event data provided'
            }), 400
        
        # Create event
        event_id = event_service.create_event(event_data)
        
        if not event_id:
            return jsonify({
                'success': False,
                'error': 'Failed to create event'
            }), 500
        
        return jsonify({
            'success': True,
            'event_id': event_id,
            'message': 'Event created successfully'
        }), 201
        
    except Exception as e:
        logger.error(f"Error creating event: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@events_bp.route('/<int:event_id>/update', methods=['PUT'])
def update_event(event_id):
    """Update existing event"""
    try:
        event_data = request.json
        
        if not event_data:
            return jsonify({
                'success': False,
                'error': 'No event data provided'
            }), 400
        
        success = event_service.update_event(event_id, event_data)
        
        if not success:
            return jsonify({
                'success': False,
                'error': 'Failed to update event'
            }), 500
        
        return jsonify({
            'success': True,
            'message': 'Event updated successfully'
        })
        
    except Exception as e:
        logger.error(f"Error updating event: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@events_bp.route('/<int:event_id>/delete', methods=['DELETE'])
def delete_event(event_id):
    """Delete event"""
    try:
        success = event_service.delete_event(event_id)
        
        if not success:
            return jsonify({
                'success': False,
                'error': 'Failed to delete event'
            }), 500
        
        return jsonify({
            'success': True,
            'message': 'Event deleted successfully'
        })
        
    except Exception as e:
        logger.error(f"Error deleting event: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500
