# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Agent Router - Routes between Event Creation and Information Agents
"""
import logging
from typing import Dict, Optional
import asyncio

logger = logging.getLogger(__name__)


class AgentRouter:
    """
    Routes queries to appropriate agent
    
    ROUTING LOGIC:
    - Event creation queries -- SPIC MACAY Agent (stable event/APR system)
    - Information queries -- Workflow Agent (multi-stage Q&A)
    """
    
    def __init__(self, agent, workflow_agent):
        """
        Initialize router with both agents
        
        Args:
            agent: SPIC MACAY event creation agent
            workflow_agent: Information workflow agent
        """
        self.agent = agent
        self.workflow_agent = workflow_agent
        logger.info(" Agent Router initialized with 2 specialized agents")
    
    def route_query(self, query: str, context: Optional[Dict] = None) -> Dict:
        """
         MAIN ROUTING METHOD
        
        Decision Tree:
        1. Check if event creation/management -- SPIC MACAY Agent
        2. Otherwise -- Workflow Agent (information queries)
        
        Args:
            query: User's message
            context: Conversation context
            
        Returns:
            Response dict with agent_type
        """
        try:
            query_lower = query.lower()
            
            # Decision: Is this event creation/management?
            if self._is_event_creation_query(query_lower, context):
                logger.info(" ROUTING -- SPIC MACAY Event Agent")
                return self._handle_event_creation(query, context)
            else:
                logger.info("  ROUTING -- Information Workflow Agent")
                return self._handle_info_workflow(query, context)
                
        except Exception as e:
            logger.error(f"Routing error: {e}")
            return {
                'success': False,
                'error': str(e),
                'response': "I encountered an error. Please try again."
            }
    
    def _is_event_creation_query(self, query: str, context: Optional[Dict]) -> bool:
        """
         Determine if query is about event creation/management
        
        Detection:
        - Action keywords: register, create, schedule, book, arrange, add
        - Event-specific: "new event", "event on [date]"
        - Context: If user is in middle of event creation flow
        
        Args:
            query: Lowercase query
            context: Conversation context
            
        Returns:
            True if event creation query
        """
        # Check context first - if already in event flow, stay there
        if context and context.get('agent_type') == 'event_creation':
            logger.debug(" Staying in event creation flow (context)")
            return True
        
        # Event/program creation keywords
        event_keywords = [
            'register event',
            'create event',
            'schedule event',
            'book event',
            'arrange event',
            'new event',
            'add event',
            'event on',           # "event on March 15th"
            'organize event',
            'plan event',
            'register an event',
            'create an event',
            'register program',
            'create program',
            'register a program',
            'create a program',
            'new program',
            'want to register',
            'want to create',
            'need to register',
            'need to create',
            'apr',                # Artist Payment Request
            'artist payment',
            # Listing/lookup intents — must stay in this agent so answers come from
            # the live database, not the general-knowledge RAG workflow agent.
            'show event',
            'show events',
            'show program',
            'show programs',
            'upcoming event',
            'upcoming events',
            'upcoming program',
            'upcoming programs',
            'list event',
            'list events',
            'list program',
            'list programs',
            'view event',
            'view events',
            'view program',
            'view programs',
            'find event',
            'find program',
            'search event',
            'search program',
            'my apr',
            'recent apr',
            # Payment reminder intents
            'pending payment',
            'payment pending',
            'payment reminder',
            'outstanding payment',
            'unpaid contribution',
            'contribution payment',
            'request for payment',
            'send payment',
        ]
        
        is_event = any(keyword in query for keyword in event_keywords)
        
        if is_event:
            logger.debug(f" Event creation query detected: {query[:50]}...")
        else:
            logger.debug(f" Information query detected: {query[:50]}...")
        
        return is_event
    
    def _handle_event_creation(self, query: str, context: Optional[Dict]) -> Dict:
        """
        Handle event creation queries via SPIC MACAY Agent
        
        Process:
        1. Pass to SPIC MACAY agent
        2. Agent handles full conversation flow
        3. Creates event + APR when ready
        
        Args:
            query: User query
            context: Conversation context
            
        Returns:
            Response from SPIC MACAY agent
        """
        try:
            # Process through SPIC MACAY agent
            response_text = self.agent.process_message(query)

            result = {
                'success': True,
                'response': response_text,
                'agent_type': 'event_creation',
                'conversation_history': self.agent.get_conversation_history()
            }

            # Surface a successful program/APR creation to the frontend (consumed once,
            # then cleared) — lets chat.js show a success toast and flush attached photos.
            creation = getattr(self.agent, 'last_creation_result', None)
            if creation:
                result['event_created'] = True
                result['event_id'] = creation.get('event_id')
                result['apr_request_id'] = creation.get('apr_request_id')
                result['pdf_download_url'] = creation.get('pdf_download_url')
                self.agent.last_creation_result = None

            # Surface a successful poster generation the same way — cleared once read.
            poster = getattr(self.agent, 'last_poster_result', None)
            if poster:
                result['poster_download_url'] = poster.get('poster_download_url')
                self.agent.last_poster_result = None

            return result

        except Exception as e:
            logger.error(f"SPIC MACAY agent error: {e}")
            return {
                'success': False,
                'error': str(e),
                'agent_type': 'event_creation',
                'response': "Error processing event request. Please try again."
            }
    
    def _handle_info_workflow(self, query: str, context: Optional[Dict]) -> Dict:
        """
        Handle information queries via Workflow Agent
        
        Process:
        1. Pass to workflow agent
        2. Multi-stage processing:
           - Query rewrite
           - Classification
           - Specialized handler
        
        Args:
            query: User query
            context: Conversation context
            
        Returns:
            Response from workflow agent
        """
        try:
            # Run async workflow
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            result = loop.run_until_complete(
                self.workflow_agent.run_workflow(query)
            )
            loop.close()
            
            result['agent_type'] = 'information_workflow'
            return result
            
        except Exception as e:
            logger.error(f"Workflow agent error: {e}")
            return {
                'success': False,
                'error': str(e),
                'agent_type': 'information_workflow',
                'response': "Error processing information request."
            }
