# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Database Operations and Validation
"""
import mysql.connector
from mysql.connector import pooling
from typing import Dict, List, Optional
import logging
import difflib

logger = logging.getLogger(__name__)
# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Database connection and management utilities
"""
import mysql.connector
from mysql.connector import Error
import logging

logger = logging.getLogger(__name__)

class DatabaseManager:
    """Database connection manager with cursor support"""
    
    def __init__(self, config: Dict):
        try:
            self.pool = pooling.MySQLConnectionPool(**config)
            logger.info("Database connection pool created successfully")
        except mysql.connector.Error as e:
            logger.error(f"Error creating connection pool: {e}")
            raise
    
    def get_connection(self):
        """Get connection from pool"""
        try:
            return self.pool.get_connection()
        except mysql.connector.Error as e:
            logger.error(f"Error getting connection from pool: {e}")
            raise
    
    def connect(self):
        """Establish database connection"""
        try:
            self.connection = mysql.connector.connect(
                host=self.config.get('host', 'localhost'),
                user=self.config.get('user', 'root'),
                password=self.config.get('password', ''),
                database=self.config.get('database', 'spic_macay'),
                autocommit=False
            )
            
            if self.connection.is_connected():
                logger.info(f"Successfully connected to database: {self.config.get('database')}")
            else:
                logger.error("Failed to connect to database")
                self.connection = None
                
        except Error as e:
            logger.error(f"Database connection error: {e}")
            self.connection = None
    
    def is_connected(self):
        """Check if database is connected"""
        return self.connection and self.connection.is_connected()
    
    def ensure_connection(self):
        """Ensure database connection is active, reconnect if needed"""
        if not self.is_connected():
            logger.warning("Database connection lost, attempting to reconnect...")
            self.connect()
        return self.is_connected()
    
    def cursor(self, dictionary=True):
        """
        Get a database cursor
        
        Args:
            dictionary: If True, return results as dictionaries
            
        Returns:
            MySQL cursor object
        """
        if not self.ensure_connection():
            raise Error("Database connection not available")
        
        return self.connection.cursor(dictionary=dictionary)
    
    def commit(self):
        """Commit current transaction"""
        if self.connection:
            self.connection.commit()
            logger.debug("Transaction committed")
    
    def rollback(self):
        """Rollback current transaction"""
        if self.connection:
            self.connection.rollback()
            logger.debug("Transaction rolled back")
    
    def execute_query(self, query: str, params=None, commit=False):
        """
        Execute a database query (convenience method)
        
        Args:
            query: SQL query string
            params: Query parameters (tuple)
            commit: Whether to commit the transaction
            
        Returns:
            Dictionary with success status and results
        """
        try:
            if not self.ensure_connection():
                return {'success': False, 'error': 'Database not connected'}
            
            cursor = self.cursor()
            cursor.execute(query, params or ())
            
            if commit:
                self.commit()
                result = {
                    'success': True,
                    'lastrowid': cursor.lastrowid,
                    'rowcount': cursor.rowcount
                }
            else:
                results = cursor.fetchall()
                result = {
                    'success': True,
                    'results': results
                }
            
            cursor.close()
            return result
                
        except Error as e:
            logger.error(f"Query execution error: {e}")
            if commit:
                self.rollback()
            return {
                'success': False,
                'error': str(e)
            }
        except Exception as e:
            logger.error(f"Unexpected error during query execution: {e}")
            if commit:
                self.rollback()
            return {
                'success': False,
                'error': str(e)
            }
    
    def fetch_one(self, query: str, params=None):
        """
        Fetch a single row
        
        Args:
            query: SQL query string
            params: Query parameters
            
        Returns:
            Dictionary with single row or None
        """
        try:
            if not self.ensure_connection():
                return None
            
            cursor = self.cursor()
            cursor.execute(query, params or ())
            result = cursor.fetchone()
            cursor.close()
            return result
            
        except Error as e:
            logger.error(f"Error fetching single row: {e}")
            return None
    
    def fetch_all(self, query: str, params=None):
        """
        Fetch all rows
        
        Args:
            query: SQL query string
            params: Query parameters
            
        Returns:
            List of dictionaries with results
        """
        try:
            if not self.ensure_connection():
                return []
            
            cursor = self.cursor()
            cursor.execute(query, params or ())
            results = cursor.fetchall()
            cursor.close()
            return results
            
        except Error as e:
            logger.error(f"Error fetching rows: {e}")
            return []
    
    def close(self):
        """Close database connection"""
        if self.connection and self.connection.is_connected():
            self.connection.close()
            logger.info("Database connection closed")


    def get_db_connection(config: dict):
        """
        Create and return DatabaseManager instance
        
        Args:
            config: Dictionary with database configuration
            
        Returns:
            DatabaseManager instance or None if failed
        """
        try:
            db_manager = DatabaseManager(config)
            if db_manager.is_connected():
                return db_manager
            else:
                logger.error("Failed to create database connection")
                return None
                
        except Exception as e:
            logger.error(f"Error creating DatabaseManager: {e}")
            return None

class DatabaseValidator:
    """Database validation and search operations"""
    
    def __init__(self, db_manager: DatabaseManager):
        self.db_manager = db_manager
    
    def search_artists(self, search_term: str) -> List[Dict]:
        """Search for artists with fuzzy matching"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = """
                SELECT 
                    tid, name, art_form, artist_type, artist_grade,
                    city, enter_state, email, phone
                FROM artists_list
                WHERE status = 1 
                AND (
                    name LIKE %s 
                    OR art_form LIKE %s
                    OR SOUNDEX(name) = SOUNDEX(%s)
                )
                ORDER BY 
                    CASE 
                        WHEN name = %s THEN 1
                        WHEN name LIKE %s THEN 2
                        ELSE 3
                    END
                LIMIT 10
            """
            
            search_pattern = f"%{search_term}%"
            exact_pattern = f"{search_term}%"
            
            cursor.execute(query, (
                search_pattern, search_pattern, search_term,
                search_term, exact_pattern
            ))
            
            results = cursor.fetchall()
            
            # Calculate relevance scores
            for result in results:
                similarity = difflib.SequenceMatcher(
                    None,
                    search_term.lower(),
                    result['name'].lower()
                ).ratio()
                result['relevance'] = round(similarity, 2)
            
            return sorted(results, key=lambda x: x['relevance'], reverse=True)
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in search_artists: {e}")
            return []
        finally:
            if conn:
                cursor.close()
                conn.close()
    
    def search_institutions(self, search_term: str, state: Optional[str] = None) -> List[Dict]:
        """Search for institutions"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = """
                SELECT 
                    sid, institution_name, city, state, 
                    pincode, email, phone, address
                FROM institution_list
                WHERE status = 1 
                AND (
                    institution_name LIKE %s 
                    OR city LIKE %s
                    OR SOUNDEX(institution_name) = SOUNDEX(%s)
                )
            """
            
            params = [f"%{search_term}%", f"%{search_term}%", search_term]
            
            if state:
                query += " AND state = %s"
                params.append(state)
            
            query += """
                ORDER BY 
                    CASE 
                        WHEN institution_name = %s THEN 1
                        WHEN institution_name LIKE %s THEN 2
                        ELSE 3
                    END
                LIMIT 10
            """
            
            params.extend([search_term, f"{search_term}%"])
            
            cursor.execute(query, params)
            results = cursor.fetchall()
            
            return results
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in search_institutions: {e}")
            return []
        finally:
            if conn:
                cursor.close()
                conn.close()
    
    def get_event_modules(self) -> List[Dict]:
        """Get available event modules"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT tid, name FROM event_module WHERE status = 1 ORDER BY name"
            cursor.execute(query)
            
            return cursor.fetchall()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_event_modules: {e}")
            return []
        finally:
            if conn:
                cursor.close()
                conn.close()
    
    def check_artist_availability(self, artist_id: int, event_date: str) -> bool:
        """Check artist availability on date"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor()
            
            query = """
                SELECT COUNT(*) as conflict_count
                FROM event_list
                WHERE artist = %s 
                AND start_date = %s
                AND status = 1
                AND event_status NOT IN ('Cancelled', 'Rejected')
            """
            
            cursor.execute(query, (artist_id, event_date))
            result = cursor.fetchone()
            
            return result[0] == 0
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in check_artist_availability: {e}")
            return True  # Default to available if check fails
        finally:
            if conn:
                cursor.close()
                conn.close()
    
    def get_artist_by_id(self, artist_id: int) -> Optional[Dict]:
        """Get artist details by ID"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT * FROM artists_list WHERE tid = %s AND status = 1"
            cursor.execute(query, (artist_id,))
            
            return cursor.fetchone()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_artist_by_id: {e}")
            return None
        finally:
            if conn:
                cursor.close()
                conn.close()
    
    def get_institution_by_id(self, institution_id: int) -> Optional[Dict]:
        """Get institution details by ID"""
        conn = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT * FROM institution_list WHERE sid = %s AND status = 1"
            cursor.execute(query, (institution_id,))
            
            return cursor.fetchone()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_institution_by_id: {e}")
            return None
        finally:
            if conn:
                cursor.close()
                conn.close()
