# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Database Operations and Validation
"""
import mysql.connector
from mysql.connector import pooling, Error
from typing import Dict, List, Optional
import logging
import difflib

logger = logging.getLogger(__name__)


class DatabaseManager:
    """Database connection manager with connection pooling"""
    
    def __init__(self, config: Dict):
        """Initialize with connection pool"""
        try:
            # Store config for later use
            self.config = config
            
            # Create connection pool
            pool_config = {
                'pool_name': 'spic_macay_pool',
                'pool_size': 5,
                'pool_reset_session': True,
                'host': config.get('host', 'localhost'),
                'user': config.get('user', 'root'),
                'password': config.get('password', ''),
                'database': config.get('database', 'spic_macay'),
                'autocommit': False
            }
            
            self.pool = pooling.MySQLConnectionPool(**pool_config)
            
            # Test the pool by getting a connection
            test_conn = self.pool.get_connection()
            if test_conn.is_connected():
                logger.info(f"Database connection pool created successfully for: {config.get('database')}")
                test_conn.close()
            
        except mysql.connector.Error as e:
            logger.error(f"Error creating connection pool: {e}")
            raise
    
    def get_connection(self):
        """Get connection from pool"""
        try:
            return self.pool.get_connection()
        except mysql.connector.Error as e:
            logger.error(f"Error getting connection from pool: {e}")
            raise
    
    def is_connected(self):
        """Check if pool is available"""
        try:
            conn = self.pool.get_connection()
            is_conn = conn.is_connected()
            conn.close()
            return is_conn
        except:
            return False
    
    def execute_query(self, query: str, params=None, commit=False):
        """
        Execute a database query using connection from pool
        
        Args:
            query: SQL query string
            params: Query parameters (tuple)
            commit: Whether to commit the transaction
            
        Returns:
            Dictionary with success status and results
        """
        conn = None
        cursor = None
        try:
            # Get connection from pool
            conn = self.get_connection()
            cursor = conn.cursor(dictionary=True)
            cursor.execute(query, params or ())
            
            if commit:
                conn.commit()
                result = {
                    'success': True,
                    'lastrowid': cursor.lastrowid,
                    'rowcount': cursor.rowcount
                }
            else:
                results = cursor.fetchall()
                result = {
                    'success': True,
                    'results': results,
                    'rowcount': cursor.rowcount
                }
            
            return result
                
        except Error as e:
            logger.error(f"Query execution error: {e}")
            if commit and conn:
                conn.rollback()
            return {
                'success': False,
                'error': str(e)
            }
        except Exception as e:
            logger.error(f"Unexpected error during query execution: {e}")
            if commit and conn:
                conn.rollback()
            return {
                'success': False,
                'error': str(e)
            }
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def fetch_one(self, query: str, params=None):
        """
        Fetch a single row
        
        Args:
            query: SQL query string
            params: Query parameters
            
        Returns:
            Dictionary with single row or None
        """
        conn = None
        cursor = None
        try:
            conn = self.get_connection()
            cursor = conn.cursor(dictionary=True)
            cursor.execute(query, params or ())
            result = cursor.fetchone()
            return result
            
        except Error as e:
            logger.error(f"Error fetching single row: {e}")
            return None
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def fetch_all(self, query: str, params=None):
        """
        Fetch all rows
        
        Args:
            query: SQL query string
            params: Query parameters
            
        Returns:
            List of dictionaries with results
        """
        conn = None
        cursor = None
        try:
            conn = self.get_connection()
            cursor = conn.cursor(dictionary=True)
            cursor.execute(query, params or ())
            results = cursor.fetchall()
            return results
            
        except Error as e:
            logger.error(f"Error fetching rows: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def close(self):
        """Close connection pool - not typically needed"""
        logger.info("Connection pool will be cleaned up automatically")


def get_db_connection(config: dict):
    """
    Create and return DatabaseManager instance
    
    Args:
        config: Dictionary with database configuration
        
    Returns:
        DatabaseManager instance or None if failed
    """
    try:
        db_manager = DatabaseManager(config)
        if db_manager.is_connected():
            logger.info("DatabaseManager created successfully")
            return db_manager
        else:
            logger.error("Failed to create database connection")
            return None
            
    except Exception as e:
        logger.error(f"Error creating DatabaseManager: {e}")
        return None


class DatabaseValidator:
    """Database validation and search operations"""
    
    def __init__(self, db_manager: DatabaseManager):
        self.db_manager = db_manager
    
    def search_artists(self, search_term: str) -> List[Dict]:
        """Search for artists with fuzzy matching"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = """
                SELECT 
                    tid, name, art_form, artist_type, artist_grade,
                    city, enter_state, email, phone
                FROM artists_list
                WHERE status = 1 
                AND (
                    name LIKE %s 
                    OR art_form LIKE %s
                    OR SOUNDEX(name) = SOUNDEX(%s)
                )
                ORDER BY 
                    CASE 
                        WHEN name = %s THEN 1
                        WHEN name LIKE %s THEN 2
                        ELSE 3
                    END
                LIMIT 10
            """
            
            search_pattern = f"%{search_term}%"
            exact_pattern = f"{search_term}%"
            
            cursor.execute(query, (
                search_pattern, search_pattern, search_term,
                search_term, exact_pattern
            ))
            
            results = cursor.fetchall()
            
            # Calculate relevance scores
            for result in results:
                similarity = difflib.SequenceMatcher(
                    None,
                    search_term.lower(),
                    result['name'].lower()
                ).ratio()
                result['relevance'] = round(similarity, 2)
            
            return sorted(results, key=lambda x: x['relevance'], reverse=True)
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in search_artists: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def search_institutions(self, search_term: str, state: Optional[str] = None) -> List[Dict]:
        """Search for institutions"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = """
                SELECT 
                    sid, institution_name, city, state, 
                    pincode, email, phone, address
                FROM institution_list
                WHERE status = 1 
                AND (
                    institution_name LIKE %s 
                    OR city LIKE %s
                    OR SOUNDEX(institution_name) = SOUNDEX(%s)
                )
            """
            
            params = [f"%{search_term}%", f"%{search_term}%", search_term]
            
            if state:
                query += " AND state = %s"
                params.append(state)
            
            query += """
                ORDER BY 
                    CASE 
                        WHEN institution_name = %s THEN 1
                        WHEN institution_name LIKE %s THEN 2
                        ELSE 3
                    END
                LIMIT 10
            """
            
            params.extend([search_term, f"{search_term}%"])
            
            cursor.execute(query, params)
            results = cursor.fetchall()
            
            return results
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in search_institutions: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def get_event_modules(self) -> List[Dict]:
        """Get available event modules"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT tid, name FROM event_module WHERE status = 1 ORDER BY name"
            cursor.execute(query)
            
            return cursor.fetchall()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_event_modules: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def check_artist_availability(self, artist_id: int, event_date: str) -> bool:
        """Check artist availability on date"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor()
            
            query = """
                SELECT COUNT(*) as conflict_count
                FROM event_list
                WHERE artist = %s 
                AND start_date = %s
                AND status = 1
                AND event_status NOT IN ('Cancelled', 'Rejected')
            """
            
            cursor.execute(query, (artist_id, event_date))
            result = cursor.fetchone()
            
            return result[0] == 0
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in check_artist_availability: {e}")
            return True  # Default to available if check fails
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def get_artist_by_id(self, artist_id: int) -> Optional[Dict]:
        """Get artist details by ID"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT * FROM artists_list WHERE tid = %s AND status = 1"
            cursor.execute(query, (artist_id,))
            
            return cursor.fetchone()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_artist_by_id: {e}")
            return None
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def get_institution_by_id(self, institution_id: int) -> Optional[Dict]:
        """Get institution details by ID"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT * FROM institution_list WHERE sid = %s AND status = 1"
            cursor.execute(query, (institution_id,))
            
            return cursor.fetchone()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_institution_by_id: {e}")
            return None
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
