# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Database Operations and Validation
"""
import mysql.connector
from mysql.connector import pooling, Error
from typing import Dict, List, Optional
import logging
import difflib
from contextlib import contextmanager

logger = logging.getLogger(__name__)


_LATIN1_TABLES = {'event_list', 'event_series', 'artists_list', 'institution_list', 'apr_payment_request',
                  'apr_payment_request2', 'event_module', 'payment_artist_detail'}   # latin1 in production (MariaDB 10.11)
_WRITE_RE = None


def latin1_params(query, params):
    """Make text latin1-safe when a statement writes to one of the portal's latin1 tables (strict mode would reject it)."""
    global _WRITE_RE
    import re
    from app.core.text_utils import latin1_safe
    if not params:
        return params
    if _WRITE_RE is None:
        _WRITE_RE = re.compile(r"^\s*(?:INSERT|UPDATE|REPLACE)\s+(?:IGNORE\s+)?(?:INTO\s+)?`?(\w+)`?", re.I)
    m = _WRITE_RE.match(query or '')
    if not m or m.group(1).lower() not in _LATIN1_TABLES:
        return params
    fix = lambda v: latin1_safe(v) if isinstance(v, str) else v
    return {k: fix(v) for k, v in params.items()} if isinstance(params, dict) else tuple(fix(v) for v in params)


class _Latin1Cursor:
    """A cursor whose writes to the portal's latin1 tables are made latin1-safe."""
    def __init__(self, cur):
        self._cur = cur

    def execute(self, query, params=None):
        return self._cur.execute(query, latin1_params(query, params))

    def __getattr__(self, name):
        return getattr(self._cur, name)


class DatabaseManager:
    """Database connection manager with connection pooling"""
    
    def __init__(self, config: Dict):
        """Initialize with connection pool"""
        try:
            # Store config for later use
            self.config = config
            
            # Create connection pool
            pool_config = {
                'pool_name': 'spic_macay_pool',
                'pool_size': 5,
                'pool_reset_session': True,
                'host': config.get('host', 'localhost'),
                'user': config.get('user', 'root'),
                'password': config.get('password', ''),
                'database': config.get('database', 'spic_macay'),
                'autocommit': False
            }
            
            self.pool = pooling.MySQLConnectionPool(**pool_config)
            
            # Test the pool by getting a connection
            test_conn = self.pool.get_connection()
            if test_conn.is_connected():
                logger.info(f"Database connection pool created successfully for: {config.get('database')}")
                test_conn.close()
            
        except mysql.connector.Error as e:
            logger.error(f"Error creating connection pool: {e}")
            raise
    
    def get_connection(self):
        """Get connection from pool"""
        try:
            return self.pool.get_connection()
        except mysql.connector.Error as e:
            logger.error(f"Error getting connection from pool: {e}")
            raise
    
    def is_connected(self):
        """Check if pool is available"""
        try:
            conn = self.pool.get_connection()
            is_conn = conn.is_connected()
            conn.close()
            return is_conn
        except:
            return False
    
    def execute_query(self, query: str, params=None, commit=False):
        params = latin1_params(query, params)
        """
        Execute a database query using connection from pool
        
        Args:
            query: SQL query string
            params: Query parameters (tuple)
            commit: Whether to commit the transaction
            
        Returns:
            Dictionary with success status and results
        """
        conn = None
        cursor = None
        try:
            # Get connection from pool
            conn = self.get_connection()
            cursor = conn.cursor(dictionary=True)
            cursor.execute(query, params or ())
            
            if commit:
                conn.commit()
                result = {
                    'success': True,
                    'lastrowid': cursor.lastrowid,
                    'rowcount': cursor.rowcount
                }
            else:
                results = cursor.fetchall()
                result = {
                    'success': True,
                    'results': results,
                    'rowcount': cursor.rowcount
                }
            
            return result
                
        except Error as e:
            logger.error(f"Query execution error: {e}")
            if commit and conn:
                conn.rollback()
            return {
                'success': False,
                'error': str(e)
            }
        except Exception as e:
            logger.error(f"Unexpected error during query execution: {e}")
            if commit and conn:
                conn.rollback()
            return {
                'success': False,
                'error': str(e)
            }
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def fetch_one(self, query: str, params=None):
        """
        Fetch a single row
        
        Args:
            query: SQL query string
            params: Query parameters
            
        Returns:
            Dictionary with single row or None
        """
        conn = None
        cursor = None
        try:
            conn = self.get_connection()
            cursor = conn.cursor(dictionary=True)
            cursor.execute(query, params or ())
            result = cursor.fetchone()
            return result
            
        except Error as e:
            logger.error(f"Error fetching single row: {e}")
            return None
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def fetch_all(self, query: str, params=None):
        """
        Fetch all rows
        
        Args:
            query: SQL query string
            params: Query parameters
            
        Returns:
            List of dictionaries with results
        """
        conn = None
        cursor = None
        try:
            conn = self.get_connection()
            cursor = conn.cursor(dictionary=True)
            cursor.execute(query, params or ())
            results = cursor.fetchall()
            return results
            
        except Error as e:
            logger.error(f"Error fetching rows: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    @contextmanager
    def transaction(self):
        """One connection and cursor for several statements, committed together or rolled back."""
        conn = self.get_connection()
        cur = conn.cursor(dictionary=True, buffered=True)
        try:
            try:
                conn.start_transaction()
            except Exception:
                pass
            yield _Latin1Cursor(cur)
            conn.commit()
        except Exception:
            try:
                conn.rollback()
            except Exception:
                pass
            raise
        finally:
            try:
                cur.close()
            finally:
                conn.close()

    def close(self):
        """Close connection pool - not typically needed"""
        logger.info("Connection pool will be cleaned up automatically")


def get_db_connection(config: dict):
    """
    Create and return DatabaseManager instance
    
    Args:
        config: Dictionary with database configuration
        
    Returns:
        DatabaseManager instance or None if failed
    """
    try:
        db_manager = DatabaseManager(config)
        if db_manager.is_connected():
            logger.info("DatabaseManager created successfully")
            return db_manager
        else:
            logger.error("Failed to create database connection")
            return None
            
    except Exception as e:
        logger.error(f"Error creating DatabaseManager: {e}")
        return None


class DatabaseValidator:
    """Database validation and search operations"""
    
    def __init__(self, db_manager: DatabaseManager):
        self.db_manager = db_manager
    
    # Honorifics/salutations not stored in artist DB — strip before searching
    _HONORIFICS = frozenset([
        'pt', 'pandit', 'ustad', 'vidushi', 'vidwan', 'vidvan', 'dr', 'swami',
        'shri', 'smt', 'shrimati', 'guru', 'prof', 'padmashri', 'padmabhushan'
    ])

    def _clean_artist_search_term(self, name: str) -> str:
        words = name.strip().split()
        cleaned = [w for w in words if w.lower().rstrip('.') not in self._HONORIFICS]
        return ' '.join(cleaned).strip() or name

    def search_artists(self, search_term: str) -> List[Dict]:
        """
        Search for artists with fuzzy matching.

        Honorifics are inconsistent in this directory — some records are stored bare
        ("Wasifuddin Dagar") and others carry the full title ("Padma Shri Ustad Faiyaz
        Wasifuddin Dagar"). So both the raw term and an honorific-stripped version are
        matched, and relevance is scored on whichever form fits better. Matching only the
        stripped term made an artist's exact stored name return nothing.
        """
        _d = getattr(self, 'directory', None)
        if _d is not None:
            from app.services import classic_bridge as _bridge
            _r = _bridge.artists(_d, search_term)
            if _r is not None:
                return _r
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)

            raw_term = (search_term or '').strip()
            clean_term = self._clean_artist_search_term(raw_term)

            query = """
                SELECT
                    tid, name, art_form, artist_type, artist_grade,
                    city, enter_state, email, phone
                FROM artists_list
                WHERE status = 1
                AND (
                    name LIKE %s
                    OR name LIKE %s
                    OR art_form LIKE %s
                    OR SOUNDEX(name) = SOUNDEX(%s)
                    OR SOUNDEX(name) = SOUNDEX(%s)
                )
                ORDER BY
                    CASE
                        WHEN name = %s THEN 1
                        WHEN name = %s THEN 2
                        WHEN name LIKE %s THEN 3
                        ELSE 4
                    END
                LIMIT 15
            """

            cursor.execute(query, (
                f"%{raw_term}%", f"%{clean_term}%", f"%{clean_term}%",
                clean_term, raw_term,
                raw_term, clean_term, f"{clean_term}%",
            ))

            results = cursor.fetchall()

            raw_lower = raw_term.lower()
            clean_lower = clean_term.lower()
            for result in results:
                stored = (result['name'] or '').strip()
                stored_clean = self._clean_artist_search_term(stored).lower()
                # Best of: term vs stored name, and both sides stripped of honorifics
                relevance = max(
                    difflib.SequenceMatcher(None, raw_lower, stored.lower()).ratio(),
                    difflib.SequenceMatcher(None, clean_lower, stored_clean).ratio(),
                )
                result['relevance'] = round(relevance, 2)

            return sorted(results, key=lambda x: x['relevance'], reverse=True)[:10]

        except mysql.connector.Error as e:
            logger.error(f"Database error in search_artists: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def search_institutions(self, search_term: str, state: Optional[str] = None) -> List[Dict]:
        """Search for institutions"""
        _d = getattr(self, 'directory', None)
        if _d is not None:
            from app.services import classic_bridge as _bridge
            _r = _bridge.institutions(_d, search_term, state)
            if _r is not None:
                return _r
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = """
                SELECT 
                    sid, institution_name, city, state, 
                    pincode, email, phone, address
                FROM institution_list
                WHERE status = 1 
                AND (
                    institution_name LIKE %s 
                    OR city LIKE %s
                    OR SOUNDEX(institution_name) = SOUNDEX(%s)
                )
            """
            
            params = [f"%{search_term}%", f"%{search_term}%", search_term]
            
            if state:
                query += " AND state = %s"
                params.append(state)
            
            query += """
                ORDER BY 
                    CASE 
                        WHEN institution_name = %s THEN 1
                        WHEN institution_name LIKE %s THEN 2
                        ELSE 3
                    END
                LIMIT 10
            """
            
            params.extend([search_term, f"{search_term}%"])
            
            cursor.execute(query, params)
            results = cursor.fetchall()
            
            return results
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in search_institutions: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def get_coordinator_by_id(self, uid) -> Optional[Dict]:
        """
        Resolve a coordinator's name and email from their portal user id.

        event_list.added_by stores this id, not a name — anything that displays the
        coordinator (a poster credit, an email) has to translate it first, or it shows
        a bare number.
        """
        try:
            uid = int(uid)
        except (TypeError, ValueError):
            return None

        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            cursor.execute(
                "SELECT uid, name, mail AS email FROM users_field_data WHERE uid = %s",
                (uid,),
            )
            return cursor.fetchone()
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_coordinator_by_id: {e}")
            return None
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()

    def search_coordinators(self, search_term: str) -> List[Dict]:
        """
        Fuzzy-search a coordinator by name to recover a known email address.

        Draws on two independent sources that both act as "coordinator" records:
        portal user accounts (users_field_data) and the contact person named on an
        institution record (institution_list.name_of_the_coordinator).
        """
        _d = getattr(self, 'directory', None)
        if _d is not None:
            from app.services import classic_bridge as _bridge
            _r = _bridge.coordinators(_d, search_term)
            if _r is not None:
                return _r
        term = (search_term or '').strip()
        if not term:
            return []

        like = f"%{term}%"
        prefix = f"{term}%"
        candidates: List[Dict] = []

        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)

            cursor.execute(
                """
                SELECT uid, name, mail
                FROM users_field_data
                WHERE status = 1 AND mail IS NOT NULL AND mail <> ''
                AND (name LIKE %s OR mail LIKE %s OR SOUNDEX(name) = SOUNDEX(%s))
                ORDER BY CASE WHEN name = %s THEN 1 WHEN name LIKE %s THEN 2 ELSE 3 END
                LIMIT 10
                """,
                (like, like, term, term, prefix),
            )
            for row in cursor.fetchall():
                candidates.append({
                    'source': 'user',
                    'uid': row['uid'],
                    'name': row['name'],
                    'email': row['mail'],
                    'institution_name': None,
                })

            cursor.execute(
                """
                SELECT sid, institution_name, name_of_the_coordinator, email
                FROM institution_list
                WHERE status = 1 AND email IS NOT NULL AND email <> ''
                AND name_of_the_coordinator IS NOT NULL AND name_of_the_coordinator <> ''
                AND (name_of_the_coordinator LIKE %s
                     OR SOUNDEX(name_of_the_coordinator) = SOUNDEX(%s))
                LIMIT 10
                """,
                (like, term),
            )
            for row in cursor.fetchall():
                candidates.append({
                    'source': 'institution',
                    'uid': None,
                    'sid': row['sid'],
                    'name': row['name_of_the_coordinator'],
                    'email': row['email'],
                    'institution_name': row['institution_name'],
                })

            term_lower = term.lower()
            for c in candidates:
                c['relevance'] = round(
                    difflib.SequenceMatcher(None, term_lower, (c['name'] or '').lower()).ratio(), 2
                )

            # One person can appear in both sources; keep the best-scoring row per address
            best_by_email: Dict[str, Dict] = {}
            for c in sorted(candidates, key=lambda x: x['relevance'], reverse=True):
                best_by_email.setdefault(c['email'].strip().lower(), c)

            return sorted(best_by_email.values(), key=lambda x: x['relevance'], reverse=True)[:5]

        except mysql.connector.Error as e:
            logger.error(f"Database error in search_coordinators: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()

    def resolve_user_uid(self, email: str = '', name: str = '') -> Optional[int]:
        """
        Map a coordinator to their numeric users_field_data.uid.

        event_list.added_by and apr_payment_request.created_by are numeric user IDs in the
        admin app's schema, so a name string written there is unreadable to that app.
        Email is matched first because it is unique; name is only a fallback.
        """
        try:
            if email and email.strip():
                row = self.db_manager.fetch_one(
                    "SELECT uid FROM users_field_data WHERE mail = %s AND status = 1 LIMIT 1",
                    (email.strip(),),
                )
                if row:
                    return int(row['uid'])

            if name and name.strip():
                row = self.db_manager.fetch_one(
                    "SELECT uid FROM users_field_data WHERE name = %s AND status = 1 LIMIT 1",
                    (name.strip(),),
                )
                if row:
                    return int(row['uid'])

            return None
        except Exception as e:
            logger.error(f"Error resolving user uid: {e}")
            return None

    def get_event_modules(self) -> List[Dict]:
        """Get available event modules"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT tid, name FROM event_module WHERE status = 1 ORDER BY name"
            cursor.execute(query)
            
            return cursor.fetchall()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_event_modules: {e}")
            return []
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def check_artist_availability(self, artist_id: int, event_date: str) -> bool:
        """Check artist availability on date"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor()
            
            query = """
                SELECT COUNT(*) as conflict_count
                FROM event_list
                WHERE artist = %s 
                AND start_date = %s
                AND status = 1
                AND event_status NOT IN ('Cancelled', 'Rejected')
            """
            
            cursor.execute(query, (artist_id, event_date))
            result = cursor.fetchone()
            
            return result[0] == 0
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in check_artist_availability: {e}")
            return True  # Default to available if check fails
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def get_artist_by_id(self, artist_id: int) -> Optional[Dict]:
        """Get artist details by ID"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT * FROM artists_list WHERE tid = %s AND status = 1"
            cursor.execute(query, (artist_id,))
            
            return cursor.fetchone()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_artist_by_id: {e}")
            return None
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
    
    def get_institution_by_id(self, institution_id: int) -> Optional[Dict]:
        """Get institution details by ID"""
        conn = None
        cursor = None
        try:
            conn = self.db_manager.get_connection()
            cursor = conn.cursor(dictionary=True)
            
            query = "SELECT * FROM institution_list WHERE sid = %s AND status = 1"
            cursor.execute(query, (institution_id,))
            
            return cursor.fetchone()
            
        except mysql.connector.Error as e:
            logger.error(f"Database error in get_institution_by_id: {e}")
            return None
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
