# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Main Conversational Agent - Unified Entry Point
Orchestrates routing between event creation and information agents
"""
from openai import OpenAI
import logging
from typing import Dict, Optional
from app.models.agent import SPICMacayAgent
from app.models.workflow_agent import WorkflowAgent
from app.models.agent_router import AgentRouter

logger = logging.getLogger(__name__)

# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Main Conversational Agent - Unified Entry Point
Orchestrates routing between event creation and information agents
"""


class ConversationalAgent:
    """
    Main unified agent with intelligent routing
    
    Architecture:
    - Entry point for all user interactions
    - Routes to specialized agents via AgentRouter
    - Maintains conversation context
    """
    
    def __init__(self, api_key: str, db_manager, event_service, notification_service):
        """
        Initialize with both specialized agents
        
        Args:
            api_key: OpenAI API key
            db_manager: Database manager
            event_service: Event service
            notification_service: Notification service
        """
        try:
            self.api_key = api_key
            self.db_manager = db_manager
            self.event_service = event_service
            self.notification_service = notification_service
            
            logger.info("Initializing ConversationalAgent components...")
            
            # Initialize SPIC MACAY event creation agent
            logger.info("Initializing SPIC MACAY Agent...")
            self.agent = SPICMacayAgent(
                api_key=api_key,
                model="gpt-4o",
                db_validator=db_manager,
                event_service=event_service,
                notification_service=notification_service
            )
            logger.info("SPIC MACAY Agent initialized successfully")
            
            # Initialize information workflow agent
            logger.info("Initializing Workflow Agent...")
            self.workflow_agent = WorkflowAgent(api_key=api_key)
            logger.info("Workflow Agent initialized successfully")
            
            # Initialize router
            logger.info("Initializing Agent Router...")
            self.router = AgentRouter(
                agent=self.agent,
                workflow_agent=self.workflow_agent
            )
            logger.info("Agent Router initialized successfully")
            
            # Track conversation context
            self.conversation_context = {}
            
            logger.info("Unified Conversational Agent initialized successfully")
            
        except Exception as e:
            logger.error(f"Failed to initialize ConversationalAgent: {e}")
            logger.error(f"Full traceback: {traceback.format_exc()}")
            raise
    
    def start_conversation(self) -> Dict:
        """
        Start a new conversation
        
        Returns:
            Welcome message dict
        """
        try:
            logger.info("Starting new conversation...")
            
            # Start SPIC MACAY agent (it has a nice greeting)
            greeting = self.agent.start_conversation()
            
            # Reset context
            self.conversation_context = {}
            
            logger.info("Conversation started successfully")
            
            return {
                'success': True,
                'response': greeting,
                'agent_type': 'greeting'
            }
            
        except Exception as e:
            logger.error(f"Error starting conversation: {e}")
            logger.error(f"Full traceback: {traceback.format_exc()}")
            return {
                'success': False,
                'error': str(e),
                'response': "Welcome! I'm here to help you with SPIC MACAY events and information. How can I assist you today?"
            }
    
    def process_message(self, user_message: str) -> Dict:
        """
        MAIN ENTRY POINT for all user messages
        
        Flow:
        1. Receive user message
        2. Route to appropriate agent
        3. Update context
        4. Return response
        
        Args:
            user_message: User's input
            
        Returns:
            Response dict from appropriate agent
        """
        try:
            if not user_message or not isinstance(user_message, str):
                logger.error(f"Invalid message type: {type(user_message)}")
                return {
                    'success': False,
                    'error': 'Invalid message format',
                    'response': 'Please provide a valid message.'
                }
            
            logger.info(f"Processing message: {user_message[:60]}...")
            
            # Route through agent router
            response = self.router.route_query(user_message, self.conversation_context)
            
            # Update context with agent type for flow continuity
            if response.get('agent_type'):
                self.conversation_context['agent_type'] = response['agent_type']
            
            logger.info(f"Response generated from {response.get('agent_type', 'unknown')} agent")
            
            return response
            
        except KeyError as e:
            logger.error(f"KeyError in process_message: {e}")
            logger.error(f"Full traceback: {traceback.format_exc()}")
            logger.error(f"Conversation context: {self.conversation_context}")
            return {
                'success': False,
                'error': f'Missing key: {str(e)}',
                'response': "I encountered an error. Please try starting a new conversation."
            }
            
        except Exception as e:
            logger.error(f"Error processing message: {e}")
            logger.error(f"Error type: {type(e).__name__}")
            logger.error(f"Full traceback: {traceback.format_exc()}")
            return {
                'success': False,
                'error': str(e),
                'response': "I apologize, but I encountered an error. Could you please try again?"
            }
    
    def reset_conversation(self):
        """Reset all conversation state"""
        try:
            logger.info("Resetting conversation...")
            self.agent.reset_conversation()
            self.conversation_context = {}
            logger.info("Conversation reset successfully")
        except Exception as e:
            logger.error(f"Error resetting conversation: {e}")
            logger.error(f"Full traceback: {traceback.format_exc()}")
    
    def get_conversation_history(self) -> Dict:
        """
        Get conversation history from active agent
        
        Returns:
            Conversation history dict
        """
        try:
            agent_type = self.conversation_context.get('agent_type')
            
            if agent_type == 'event_creation':
                return {
                    'agent_type': 'event_creation',
                    'history': self.agent.get_conversation_history()
                }
            else:
                return {
                    'agent_type': 'information',
                    'history': []
                }
        except Exception as e:
            logger.error(f"Error getting conversation history: {e}")
            logger.error(f"Full traceback: {traceback.format_exc()}")
            return {
                'agent_type': 'unknown',
                'history': [],
                'error': str(e)
            }
