# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Notification Service for SPIC MACAY Event Agent
Handles email notifications and calendar invites
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from ics import Calendar, Event as ICSEvent
import logging

logger = logging.getLogger(__name__)

class NotificationService:
    """Service for sending email notifications"""
    
    def __init__(self, smtp_config: dict):
        """
        Initialize notification service
        
        Args:
            smtp_config: SMTP configuration dictionary
        """
        self.smtp_config = smtp_config
        self.enabled = bool(smtp_config.get('user') and smtp_config.get('password'))
        
        if not self.enabled:
            logger.warning("Email notifications disabled - SMTP credentials not configured")
    
    def send_event_confirmation(self, event_data: dict, recipients: list,
                               pdf_bytes: bytes = None, photo_attachments: list = None) -> bool:
        """
        Send program confirmation email with optional APR PDF and photo attachments.

        Args:
            event_data:        Event/program details dictionary
            recipients:        List of email addresses
            pdf_bytes:         Optional APR PDF as bytes — attached when provided
            photo_attachments: Optional list of raw image bytes — attached when provided

        Returns:
            True if sent successfully, False otherwise
        """
        if not self.enabled:
            logger.info("Email notifications disabled, skipping")
            return False

        try:
            # Use 'mixed' when we have attachments so we can combine HTML + files
            msg = MIMEMultipart('mixed')
            msg['Subject'] = f"SPIC MACAY Artist Payment Request (APR) Confirmation - {event_data.get('title', 'New Program')}"
            msg['From'] = self.smtp_config['from_email']
            msg['To'] = ', '.join(recipients)

            # HTML body
            html_body = self._create_confirmation_email_html(event_data)
            html_part = MIMEText(html_body, 'html')
            msg.attach(html_part)

            # APR PDF attachment
            if pdf_bytes:
                try:
                    request_id = event_data.get('request_id', 'APR')
                    pdf_part = MIMEBase('application', 'pdf')
                    pdf_part.set_payload(pdf_bytes)
                    encoders.encode_base64(pdf_part)
                    pdf_part.add_header(
                        'Content-Disposition', 'attachment',
                        filename=f'APR_{request_id}.pdf'
                    )
                    msg.attach(pdf_part)
                    logger.info("APR PDF attached to email")
                except Exception as e:
                    logger.warning(f"Failed to attach APR PDF: {e}")

            # Optional program photos
            for idx, photo_bytes in enumerate(photo_attachments or [], 1):
                try:
                    img_part = MIMEBase('image', 'jpeg')
                    img_part.set_payload(photo_bytes)
                    encoders.encode_base64(img_part)
                    img_part.add_header(
                        'Content-Disposition', 'attachment',
                        filename=f'program_photo_{idx}.jpg'
                    )
                    msg.attach(img_part)
                except Exception as e:
                    logger.warning(f"Failed to attach program photo {idx}: {e}")
            if photo_attachments:
                logger.info(f"{len(photo_attachments)} program photo(s) attached to email")

            # Calendar invite
            try:
                calendar_invite = self._create_calendar_invite(event_data)
                if calendar_invite:
                    cal_part = MIMEBase('text', 'calendar', method='REQUEST')
                    cal_part.set_payload(calendar_invite.encode('utf-8'))
                    encoders.encode_base64(cal_part)
                    cal_part.add_header('Content-Disposition', 'attachment', filename='invite.ics')
                    msg.attach(cal_part)
            except Exception as e:
                logger.warning(f"Failed to create calendar invite: {e}")

            # Send
            with smtplib.SMTP(self.smtp_config['host'], self.smtp_config['port']) as server:
                server.starttls()
                server.login(self.smtp_config['user'], self.smtp_config['password'])
                server.send_message(msg)

            logger.info(f"Event confirmation sent to {recipients}")
            return True

        except Exception as e:
            logger.error(f"Failed to send event confirmation: {e}")
            return False
    
    def _create_confirmation_email_html(self, event_data: dict) -> str:
        """Create HTML email body for program (APR) confirmation"""

        event_id = event_data.get('event_id', 'N/A')
        request_id = event_data.get('request_id', 'N/A')
        custom_apr = event_data.get('custom_apr', 'N/A')
        title = event_data.get('title', 'SPIC MACAY Program')
        module_name = event_data.get('module_name', 'Program')
        artist_name = event_data.get('artist_name', 'N/A')
        art_form = event_data.get('art_form', 'N/A')
        accompanying_artists = event_data.get('accompanying_artists', '')
        start_date = event_data.get('start_date', 'N/A')
        event_time = event_data.get('event_time', 'N/A')
        institution_name = event_data.get('institution_name', 'N/A')
        venue = event_data.get('venue', 'N/A')
        city = event_data.get('city', 'N/A')
        state = event_data.get('state', 'N/A')
        attendees = event_data.get('attendees', 'N/A')
        accompanying_row = f"""
                <div class="detail-row">
                    <div class="detail-label">Accompanying:</div>
                    <div class="detail-value">{accompanying_artists}</div>
                </div>""" if accompanying_artists else ""
        
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }}
        .container {{
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background: linear-gradient(135deg, #8B0000 0%, #DC143C 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 10px 10px 0 0;
        }}
        .content {{
            background: #f9f9f9;
            padding: 30px;
            border-radius: 0 0 10px 10px;
        }}
        .event-details {{
            background: white;
            padding: 20px;
            margin: 20px 0;
            border-radius: 8px;
            border-left: 4px solid #8B0000;
        }}
        .detail-row {{
            display: flex;
            padding: 10px 0;
            border-bottom: 1px solid #eee;
        }}
        .detail-label {{
            font-weight: bold;
            width: 150px;
            color: #8B0000;
        }}
        .detail-value {{
            flex: 1;
        }}
        .apr-box {{
            background: #fff3cd;
            border: 2px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
            border-radius: 8px;
        }}
        .footer {{
            text-align: center;
            color: #666;
            font-size: 12px;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎭 SPIC MACAY Artist Payment Request (APR) Confirmation</h1>
            <p>Society for the Promotion of Indian Classical Music and Culture Amongst Youth</p>
        </div>

        <div class="content">
            <p>Namaste,</p>

            <p>Your SPIC MACAY program has been successfully registered and an Artist Payment Request (APR) has been created.</p>

            <div class="apr-box">
                <strong>📋 APR Details:</strong><br>
                <strong>Program ID:</strong> #{event_id}<br>
                <strong>APR Request ID:</strong> {request_id}<br>
                <strong>Custom APR:</strong> {custom_apr}
            </div>

            <div class="event-details">
                <h3 style="color: #8B0000; margin-top: 0;">Program Details</h3>

                <div class="detail-row">
                    <div class="detail-label">Program Title:</div>
                    <div class="detail-value">{title}</div>
                </div>

                <div class="detail-row">
                    <div class="detail-label">Program Type:</div>
                    <div class="detail-value">{module_name}</div>
                </div>

                <div class="detail-row">
                    <div class="detail-label">Artist:</div>
                    <div class="detail-value">{artist_name}</div>
                </div>

                <div class="detail-row">
                    <div class="detail-label">Art Form:</div>
                    <div class="detail-value">{art_form}</div>
                </div>
                {accompanying_row}
                <div class="detail-row">
                    <div class="detail-label">Date:</div>
                    <div class="detail-value">{start_date}</div>
                </div>
                
                <div class="detail-row">
                    <div class="detail-label">Time:</div>
                    <div class="detail-value">{event_time}</div>
                </div>
                
                <div class="detail-row">
                    <div class="detail-label">Institution:</div>
                    <div class="detail-value">{institution_name}</div>
                </div>
                
                <div class="detail-row">
                    <div class="detail-label">Venue:</div>
                    <div class="detail-value">{venue}</div>
                </div>
                
                <div class="detail-row">
                    <div class="detail-label">Location:</div>
                    <div class="detail-value">{city}, {state}</div>
                </div>
                
                <div class="detail-row" style="border-bottom: none;">
                    <div class="detail-label">Expected Attendees:</div>
                    <div class="detail-value">{attendees}</div>
                </div>
            </div>
            
            <p style="margin-top: 20px;">
                <strong>📅 Calendar Invite:</strong> A calendar invite (.ics file) is attached to this email. 
                Please add it to your calendar.
            </p>
            
            <p style="margin-top: 20px;">
                For any queries or changes, please contact the SPIC MACAY coordination team.
            </p>
            
            <p>Thank you for promoting Indian classical arts and culture!</p>
            
            <p style="margin-top: 30px;">
                <strong>SPIC MACAY Team</strong><br>
                <em>Spreading the essence of Indian heritage</em>
            </p>
        </div>
        
        <div class="footer">
            <p>This is an automated email from SPIC MACAY Program Management System</p>
            <p>&copy; {datetime.now().year} SPIC MACAY. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
"""
        return html
    
    def _create_calendar_invite(self, event_data: dict) -> str:
        """
        Create ICS calendar invite
        
        Args:
            event_data: Event details
            
        Returns:
            ICS file content as string
        """
        try:
            calendar = Calendar()
            event = ICSEvent()
            
            # Set event details
            event.name = event_data.get('title', 'SPIC MACAY Event')
            
            # Parse date
            start_date_str = event_data.get('start_date')
            if start_date_str:
                event.begin = datetime.strptime(start_date_str, '%Y-%m-%d')
            
            # Set location
            location_parts = [
                event_data.get('venue', ''),
                event_data.get('institution_name', ''),
                event_data.get('city', ''),
                event_data.get('state', '')
            ]
            event.location = ', '.join([p for p in location_parts if p])
            
            # Set description
            description_parts = [
                f"Artist: {event_data.get('artist_name', 'N/A')}",
                f"Art Form: {event_data.get('art_form', 'N/A')}",
                f"Event Type: {event_data.get('module_name', 'N/A')}",
                f"Expected Attendees: {event_data.get('attendees', 'N/A')}",
                f"APR Request ID: {event_data.get('request_id', 'N/A')}",
                f"Custom APR: {event_data.get('custom_apr', 'N/A')}"
            ]
            event.description = '\n'.join(description_parts)
            
            calendar.events.add(event)
            
            return str(calendar)
            
        except Exception as e:
            logger.error(f"Error creating calendar invite: {e}")
            return None

    def send_payment_reminder(self, reminder_data: dict, recipients: list,
                               pdf_bytes: bytes = None, cc_recipients: list = None,
                               poster_bytes: bytes = None) -> bool:
        """
        Send a "Request for Payment" reminder email to a host institution, using the
        standard template in email_templates/payment_reminder_template.txt, with the
        Request for Payment PDF attached.

        Args:
            reminder_data: {'institute_coordinator_name': ..., 'coordinator_name': ...}
            recipients:    List of email addresses (the institution's email)
            pdf_bytes:     Optional Request for Payment PDF as bytes — attached when provided
            cc_recipients: Optional list of addresses to CC — the SPIC MACAY coordinator
                           who requested the reminder is always CC'd here when known
            poster_bytes:  Optional program poster image, re-attached from when it was
                           first uploaded during APR creation

        Returns:
            True if sent successfully, False otherwise
        """
        if not self.enabled:
            logger.info("Email notifications disabled, skipping payment reminder")
            return False

        try:
            body_text = self._render_payment_reminder_body(reminder_data)
            body_html = self._create_payment_reminder_html(reminder_data)

            msg = MIMEMultipart('mixed')
            msg['Subject'] = f"Thank You — Programme Feedback & Contribution Details – SPIC MACAY ({reminder_data.get('institution_name', '')})".strip()
            msg['From'] = self.smtp_config['from_email']
            msg['To'] = ', '.join(recipients)
            cc_list = self._outbound_cc(recipients, *(cc_recipients or []))
            if cc_list:
                msg['Cc'] = ', '.join(cc_list)

            # Plain text alternative first, HTML preferred — mail clients render the last
            # part in a multipart/alternative that they understand, so HTML goes last.
            alt = MIMEMultipart('alternative')
            alt.attach(MIMEText(body_text, 'plain'))
            alt.attach(MIMEText(body_html, 'html'))
            msg.attach(alt)

            if pdf_bytes:
                try:
                    pdf_part = MIMEBase('application', 'pdf')
                    pdf_part.set_payload(pdf_bytes)
                    encoders.encode_base64(pdf_part)
                    pdf_part.add_header(
                        'Content-Disposition', 'attachment',
                        filename='Request_for_Payment.pdf'
                    )
                    msg.attach(pdf_part)
                except Exception as e:
                    logger.warning(f"Failed to attach payment request PDF: {e}")

            if poster_bytes:
                try:
                    poster_part = MIMEBase('image', 'jpeg')
                    poster_part.set_payload(poster_bytes)
                    encoders.encode_base64(poster_part)
                    poster_part.add_header(
                        'Content-Disposition', 'attachment',
                        filename='program_poster.jpg'
                    )
                    msg.attach(poster_part)
                except Exception as e:
                    logger.warning(f"Failed to attach program poster: {e}")

            with smtplib.SMTP(self.smtp_config['host'], self.smtp_config['port']) as server:
                server.starttls()
                server.login(self.smtp_config['user'], self.smtp_config['password'])
                server.send_message(msg)

            logger.info(f"Payment reminder sent to {recipients}")
            return True

        except Exception as e:
            logger.error(f"Failed to send payment reminder: {e}")
            return False

    def _render_payment_reminder_body(self, reminder_data: dict) -> str:
        """Load email_templates/payment_reminder_template.txt and fill in placeholders."""
        import os

        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        template_path = os.path.join(base_dir, 'email_templates', 'payment_reminder_template.txt')

        try:
            with open(template_path, 'r', encoding='utf-8') as fh:
                template = fh.read()
        except Exception as e:
            logger.error(f"Could not load payment reminder template at {template_path}: {e}")
            template = ("Dear Sir/Maam,\n\nThis is a reminder to process your SPIC MACAY "
                        "program contribution.\n\nWarm regards,\n{coordinator_name}\nSPIC MACAY")

        institute_coordinator_name = (reminder_data.get('institute_coordinator_name') or '').strip()
        salutation = f"Dear {institute_coordinator_name}," if institute_coordinator_name else "Dear Sir/Maam,"

        feedback_url = (self.smtp_config.get('feedback_form_url') or '').strip()
        feedback_line = f"Submit Feedback: {feedback_url}" if feedback_url else \
            "(Feedback form link to follow separately)"

        coordinator_name = reminder_data.get('coordinator_name') or 'SPIC MACAY Team'

        # Template's "Subject:" line is metadata for the coordinator, not part of the mail body
        lines = template.split('\n')
        if lines and lines[0].lower().startswith('subject:'):
            lines = lines[1:]
        body_template = '\n'.join(lines).lstrip('\n')

        return body_template.format(
            salutation=salutation,
            feedback_form_line=feedback_line,
            coordinator_name=coordinator_name,
        )

    def _create_payment_reminder_html(self, reminder_data: dict) -> str:
        """Rich HTML version of the payment reminder — same yellow/red SPIC MACAY branding
        as the APR confirmation email, with a scannable fact list of what's owed."""
        institute_coordinator_name = (reminder_data.get('institute_coordinator_name') or '').strip()
        salutation = f"Dear {institute_coordinator_name}," if institute_coordinator_name else "Dear Sir/Madam,"

        coordinator_name = reminder_data.get('coordinator_name') or 'SPIC MACAY Team'
        institution_name = reminder_data.get('institution_name') or 'N/A'
        module_name      = reminder_data.get('module_name') or 'Program'
        artist_name      = reminder_data.get('artist_name') or 'N/A'
        request_id       = reminder_data.get('request_id') or 'N/A'
        chapter          = reminder_data.get('chapter') or ''

        event_date = reminder_data.get('event_date') or ''
        try:
            event_date = datetime.strptime(event_date, '%Y-%m-%d').strftime('%d %b %Y')
        except Exception:
            pass
        event_date = event_date or 'N/A'

        amount = reminder_data.get('amount')
        amount_str = f"₹{amount:,.0f}" if isinstance(amount, (int, float)) else (str(amount) if amount else 'N/A')

        feedback_url = (self.smtp_config.get('feedback_form_url') or '').strip()
        feedback_row = f"""
                <tr>
                    <td colspan="2" style="padding-top:14px;">
                        <a href="{feedback_url}" style="color:#B3161C; font-weight:700; text-decoration:none;">
                            📝 Share your feedback on this program
                        </a>
                    </td>
                </tr>""" if feedback_url else ""

        return f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #3D2B00; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{
            background: linear-gradient(135deg, #FDEFB8 0%, #F7C948 55%, #E8A800 100%);
            color: #8B0000; padding: 30px; text-align: center;
            border-radius: 10px 10px 0 0; border-bottom: 4px solid #B3161C;
        }}
        .header h1 {{ margin: 0; font-size: 22px; }}
        .header p {{ margin: 6px 0 0; opacity: .85; font-size: 13px; }}
        .content {{ background: #FFFBEF; padding: 30px; border-radius: 0 0 10px 10px; }}
        .pill {{
            display: inline-block; background: #fff3cd; border: 2px solid #ffc107;
            color: #7a5b00; font-weight: 700; padding: 6px 16px; border-radius: 20px;
            font-size: 13px; margin-bottom: 18px;
        }}
        .facts {{
            background: white; border-radius: 10px; border-left: 4px solid #B3161C;
            padding: 4px 20px; margin: 20px 0; box-shadow: 0 2px 8px rgba(0,0,0,.04);
        }}
        .facts table {{ width: 100%; border-collapse: collapse; }}
        .facts td {{ padding: 10px 0; border-bottom: 1px solid #F0E6C8; font-size: 14px; vertical-align: top; }}
        .facts tr:last-child td {{ border-bottom: none; }}
        .facts td.label {{ font-weight: 700; color: #8B0000; width: 46%; }}
        .amount-box {{
            background: linear-gradient(135deg, #FDEFB8 0%, #F7C948 100%);
            border: 2px solid #E8A800; border-radius: 10px; padding: 16px 20px;
            margin: 20px 0; text-align: center;
        }}
        .amount-box .label {{ font-size: 12px; text-transform: uppercase; letter-spacing: .06em; color: #7a5b00; font-weight: 700; }}
        .amount-box .value {{ font-size: 28px; font-weight: 800; color: #8B0000; margin-top: 4px; }}
        .footer {{ text-align: center; color: #7A6050; font-size: 12px; margin-top: 26px; padding-top: 16px; border-top: 1px solid #EEE0BE; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎭 SPIC MACAY</h1>
            <p>Society for the Promotion of Indian Classical Music And Culture Amongst Youth</p>
        </div>
        <div class="content">
            <p>{salutation}</p>
            <span class="pill">🙏 With Our Thanks</span>
            <p>
                Thank you for hosting this programme under the SPIC MACAY movement. We hope the
                students and faculty enjoyed the session and that it opened a door to India's rich
                cultural heritage for them.
            </p>

            <div class="facts">
                <table>
                    <tr><td class="label">Institute Name</td><td>{institution_name}</td></tr>
                    <tr><td class="label">Event Date / Type</td><td>{event_date} / {module_name}</td></tr>
                    <tr><td class="label">Artist(s) Featured</td><td>{artist_name}</td></tr>
                    <tr><td class="label">Reference No.</td><td>{request_id}</td></tr>
                    {feedback_row}
                </table>
            </div>

            <div class="amount-box">
                <div class="label">Contribution towards the programme</div>
                <div class="value">{amount_str}</div>
            </div>

            <p>The details are enclosed as a PDF along with our bank particulars, should your office
               wish to process the contribution at its convenience. Contributions from host institutions
               are what allow us to take artists to more schools and colleges across the country.</p>

            <p>If this has already been arranged, please do treat this note simply as an
               acknowledgement, with our thanks.</p>

            <p style="margin-top: 24px;">
                Warm regards,<br>
                <strong>{coordinator_name}</strong><br>
                SPIC MACAY{f' {chapter}' if chapter else ''}
            </p>
        </div>
        <div class="footer">
            <p>This is an automated email from the SPIC MACAY Supatra Platform.</p>
            <p>&copy; {datetime.now().year} SPIC MACAY. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
"""

    # ── Weekly reports ───────────────────────────────────────────────────────

    _REPORT_STYLE = """
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #3D2B00; }
        .container { max-width: 680px; margin: 0 auto; padding: 20px; }
        .header {
            background: linear-gradient(135deg, #FDEFB8 0%, #F7C948 55%, #E8A800 100%);
            color: #8B0000; padding: 26px 30px; text-align: center;
            border-radius: 10px 10px 0 0; border-bottom: 4px solid #B3161C;
        }
        .header h1 { margin: 0; font-size: 21px; }
        .header p { margin: 6px 0 0; opacity: .85; font-size: 13px; }
        .content { background: #FFFBEF; padding: 28px; border-radius: 0 0 10px 10px; }
        .stat-row { display: flex; gap: 14px; margin: 10px 0 22px; flex-wrap: wrap; }
        .stat-tile {
            flex: 1; min-width: 140px; background: white; border-radius: 10px;
            border-left: 4px solid #B3161C; padding: 14px 16px; box-shadow: 0 2px 8px rgba(0,0,0,.04);
        }
        .stat-tile .n { font-size: 26px; font-weight: 800; color: #8B0000; }
        .stat-tile .lbl { font-size: 12px; color: #7A6050; text-transform: uppercase; letter-spacing: .04em; }
        table.report-table { width: 100%; border-collapse: collapse; margin: 14px 0; font-size: 13px; }
        table.report-table th {
            background: #5B1414; color: white; text-align: left; padding: 8px 10px; font-size: 12px;
        }
        table.report-table td { padding: 7px 10px; border-bottom: 1px solid #F0E6C8; }
        table.report-table tr:nth-child(even) td { background: #FFF6DF; }
        .empty-note {
            background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px;
            padding: 12px 16px; color: #7a5b00; font-weight: 600;
        }
        .attach-note { font-size: 13px; color: #7A6050; margin-top: 4px; }
        .footer { text-align: center; color: #7A6050; font-size: 12px; margin-top: 24px; padding-top: 16px; border-top: 1px solid #EEE0BE; }
    """

    def send_weekly_events_report(self, report_data: dict, recipients: list,
                                   excel_bytes: bytes = None) -> bool:
        """Weekly recap: programs logged this week + academic-year-to-date totals, with
        an Excel attachment of the week's programs."""
        if not self.enabled:
            logger.info("Email notifications disabled, skipping weekly events report")
            return False
        try:
            html_body = self._create_weekly_events_html(report_data)

            msg = MIMEMultipart('mixed')
            week_count = report_data.get('week_count', 0)
            msg['Subject'] = f"Weekly Programs Recap — {week_count} new this week ({report_data.get('generated_on', '')})"
            msg['From'] = self.smtp_config['from_email']
            msg['To'] = ', '.join(recipients)
            msg.attach(MIMEText(html_body, 'html'))

            if excel_bytes:
                try:
                    part = MIMEBase(
                        'application',
                        'vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                    )
                    part.set_payload(excel_bytes)
                    encoders.encode_base64(part)
                    part.add_header('Content-Disposition', 'attachment', filename='programs_this_week.xlsx')
                    msg.attach(part)
                except Exception as e:
                    logger.warning(f"Failed to attach weekly programs Excel: {e}")

            with smtplib.SMTP(self.smtp_config['host'], self.smtp_config['port']) as server:
                server.starttls()
                server.login(self.smtp_config['user'], self.smtp_config['password'])
                server.send_message(msg)

            logger.info(f"Weekly events report sent to {recipients}")
            return True
        except Exception as e:
            logger.error(f"Failed to send weekly events report: {e}", exc_info=True)
            return False

    def _create_weekly_events_html(self, report_data: dict) -> str:
        week_events = report_data.get('week_events') or []
        week_count = report_data.get('week_count', 0)
        academic_year = report_data.get('academic_year', 'N/A')
        ay_total = report_data.get('academic_year_total', 0)

        if week_events:
            rows = []
            for ev in week_events[:25]:
                start_date = ev.get('start_date') or ''
                try:
                    start_date = datetime.strptime(str(start_date), '%Y-%m-%d').strftime('%d %b %Y')
                except Exception:
                    pass
                rows.append(
                    f"<tr><td>{ev.get('title') or ev.get('module_name') or 'N/A'}</td>"
                    f"<td>{ev.get('artist_name') or 'N/A'}</td>"
                    f"<td>{ev.get('institution_name') or 'N/A'}</td>"
                    f"<td>{start_date}</td>"
                    f"<td>{ev.get('event_status') or ''}</td></tr>"
                )
            more_note = (f"<p class='attach-note'>+ {len(week_events) - 25} more in the attached "
                         f"spreadsheet.</p>" if len(week_events) > 25 else "")
            table_html = f"""
            <table class="report-table">
                <tr><th>Title</th><th>Artist</th><th>Institution</th><th>Date</th><th>Status</th></tr>
                {''.join(rows)}
            </table>
            {more_note}
            <p class="attach-note">📎 Full details attached as programs_this_week.xlsx</p>
            """
        else:
            table_html = '<p class="empty-note">No new programs were logged this week.</p>'

        return f"""
<!DOCTYPE html>
<html>
<head><style>{self._REPORT_STYLE}</style></head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎭 SPIC MACAY — Weekly Programs Recap</h1>
            <p>Society for the Promotion of Indian Classical Music And Culture Amongst Youth</p>
        </div>
        <div class="content">
            <p>Namaste,</p>
            <p>Here's this week's snapshot of programs logged in the system.</p>

            <div class="stat-row">
                <div class="stat-tile">
                    <div class="n">{week_count}</div>
                    <div class="lbl">New programs this week</div>
                </div>
                <div class="stat-tile">
                    <div class="n">{ay_total}</div>
                    <div class="lbl">Total programs — AY {academic_year}</div>
                </div>
            </div>

            <h3 style="color:#8B0000;">Programs Logged This Week</h3>
            {table_html}

            <p style="margin-top: 24px;">
                Warm regards,<br>
                <strong>SPIC MACAY Supatra Platform</strong>
            </p>
        </div>
        <div class="footer">
            <p>This is an automated weekly email from the SPIC MACAY Supatra Platform.</p>
            <p>&copy; {datetime.now().year} SPIC MACAY. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
"""

    def send_weekly_artist_report(self, report_data: dict, recipients: list,
                                   week_excel_bytes: bytes = None,
                                   full_excel_bytes: bytes = None) -> bool:
        """Weekly recap: artists added this week, with two Excel attachments — the
        week's new artists, and the complete artist directory."""
        if not self.enabled:
            logger.info("Email notifications disabled, skipping weekly artist report")
            return False
        try:
            html_body = self._create_weekly_artists_html(report_data)

            msg = MIMEMultipart('mixed')
            week_count = report_data.get('week_count', 0)
            msg['Subject'] = f"Weekly Artist Directory Recap — {week_count} new this week ({report_data.get('generated_on', '')})"
            msg['From'] = self.smtp_config['from_email']
            msg['To'] = ', '.join(recipients)
            msg.attach(MIMEText(html_body, 'html'))

            for excel_bytes, filename in [
                (week_excel_bytes, 'artists_added_this_week.xlsx'),
                (full_excel_bytes, 'full_artist_directory.xlsx'),
            ]:
                if not excel_bytes:
                    continue
                try:
                    part = MIMEBase(
                        'application',
                        'vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                    )
                    part.set_payload(excel_bytes)
                    encoders.encode_base64(part)
                    part.add_header('Content-Disposition', 'attachment', filename=filename)
                    msg.attach(part)
                except Exception as e:
                    logger.warning(f"Failed to attach {filename}: {e}")

            with smtplib.SMTP(self.smtp_config['host'], self.smtp_config['port']) as server:
                server.starttls()
                server.login(self.smtp_config['user'], self.smtp_config['password'])
                server.send_message(msg)

            logger.info(f"Weekly artist report sent to {recipients}")
            return True
        except Exception as e:
            logger.error(f"Failed to send weekly artist report: {e}", exc_info=True)
            return False

    def _create_weekly_artists_html(self, report_data: dict) -> str:
        week_artists = report_data.get('week_artists') or []
        week_count = report_data.get('week_count', 0)
        total_artists = report_data.get('total_artists', 0)

        if week_artists:
            rows = []
            for a in week_artists[:25]:
                rows.append(
                    f"<tr><td>{a.get('name') or 'N/A'}</td>"
                    f"<td>{a.get('art_form') or ''}</td>"
                    f"<td>{a.get('city') or ''}{', ' + a['state'] if a.get('state') else ''}</td>"
                    f"<td>{a.get('email') or ''}</td></tr>"
                )
            more_note = (f"<p class='attach-note'>+ {len(week_artists) - 25} more in the attached "
                         f"spreadsheet.</p>" if len(week_artists) > 25 else "")
            table_html = f"""
            <table class="report-table">
                <tr><th>Name</th><th>Art Form</th><th>Location</th><th>Email</th></tr>
                {''.join(rows)}
            </table>
            {more_note}
            """
        else:
            table_html = '<p class="empty-note">No new artists were added to the directory this week.</p>'

        return f"""
<!DOCTYPE html>
<html>
<head><style>{self._REPORT_STYLE}</style></head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎭 SPIC MACAY — Weekly Artist Directory Recap</h1>
            <p>Society for the Promotion of Indian Classical Music And Culture Amongst Youth</p>
        </div>
        <div class="content">
            <p>Namaste,</p>
            <p>Here's this week's snapshot of the artist directory.</p>

            <div class="stat-row">
                <div class="stat-tile">
                    <div class="n">{week_count}</div>
                    <div class="lbl">New artists this week</div>
                </div>
                <div class="stat-tile">
                    <div class="n">{total_artists}</div>
                    <div class="lbl">Total artists in directory</div>
                </div>
            </div>

            <h3 style="color:#8B0000;">Artists Added This Week</h3>
            {table_html}

            <p class="attach-note">📎 Two spreadsheets attached: this week's new artists
               (artists_added_this_week.xlsx), and the complete directory
               (full_artist_directory.xlsx).</p>

            <p style="margin-top: 24px;">
                Warm regards,<br>
                <strong>SPIC MACAY Supatra Platform</strong>
            </p>
        </div>
        <div class="footer">
            <p>This is an automated weekly email from the SPIC MACAY Supatra Platform.</p>
            <p>&copy; {datetime.now().year} SPIC MACAY. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
"""

    # ── Programme lifecycle emails ───────────────────────────────────────────

    _LIFECYCLE_STYLE = """
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #3D2B00; }
        .container { max-width: 620px; margin: 0 auto; padding: 20px; }
        .header {
            background: linear-gradient(135deg, #FDEFB8 0%, #F7C948 55%, #E8A800 100%);
            color: #8B0000; padding: 28px 30px; text-align: center;
            border-radius: 10px 10px 0 0; border-bottom: 4px solid #B3161C;
        }
        .header h1 { margin: 0; font-size: 21px; }
        .header p { margin: 6px 0 0; opacity: .85; font-size: 13px; }
        .content { background: #FFFBEF; padding: 28px; border-radius: 0 0 10px 10px; }
        .pill {
            display: inline-block; background: #fff3cd; border: 2px solid #ffc107;
            color: #7a5b00; font-weight: 700; padding: 6px 16px; border-radius: 20px;
            font-size: 13px; margin-bottom: 16px;
        }
        .facts {
            background: white; border-radius: 10px; border-left: 4px solid #B3161C;
            padding: 4px 20px; margin: 18px 0; box-shadow: 0 2px 8px rgba(0,0,0,.04);
        }
        .facts table { width: 100%; border-collapse: collapse; }
        .facts td { padding: 9px 0; border-bottom: 1px solid #F0E6C8; font-size: 14px; vertical-align: top; }
        .facts tr:last-child td { border-bottom: none; }
        .facts td.label { font-weight: 700; color: #8B0000; width: 42%; }
        .amount-box {
            background: linear-gradient(135deg, #FDEFB8 0%, #F7C948 100%);
            border: 2px solid #E8A800; border-radius: 10px; padding: 16px 20px;
            margin: 18px 0; text-align: center;
        }
        .amount-box .label { font-size: 12px; text-transform: uppercase; letter-spacing: .06em; color: #7a5b00; font-weight: 700; }
        .amount-box .value { font-size: 28px; font-weight: 800; color: #8B0000; margin-top: 4px; }
        .sop h3 { color: #8B0000; font-size: 15px; margin: 18px 0 6px; }
        .sop ul { margin: 0 0 10px; padding-left: 20px; }
        .sop li { font-size: 13.5px; margin-bottom: 4px; }
        .attach-note { font-size: 13px; color: #7A6050; margin-top: 14px; }
        .footer { text-align: center; color: #7A6050; font-size: 12px; margin-top: 24px; padding-top: 16px; border-top: 1px solid #EEE0BE; }
    """

    @staticmethod
    def _fmt_date(value) -> str:
        """Render a stored date as '09 Mar 2026', leaving anything unparseable as-is."""
        if not value:
            return 'N/A'
        text = str(value)
        for fmt in ('%Y-%m-%d', '%d-%m-%Y'):
            try:
                return datetime.strptime(text[:10], fmt).strftime('%d %b %Y')
            except ValueError:
                continue
        return text

    @staticmethod
    def _fmt_amount(amount) -> str:
        try:
            return f"₹{float(amount):,.0f}"
        except (TypeError, ValueError):
            return str(amount) if amount else 'N/A'

    def _outbound_cc(self, to_recipients: list, *addresses) -> list:
        """
        CC list for anything addressed outward to an institution or an artist: the
        coordinator handling the programme, plus the central/finance team configured in
        APR_CC_RECIPIENTS — so the office always holds a copy of what went out in its name.

        Blanks are dropped, addresses are de-duplicated case-insensitively, and anyone
        already in the To line is skipped so they don't receive it twice.
        """
        seen = {(a or '').strip().lower() for a in (to_recipients or []) if a}
        cc = []
        candidates = list(addresses) + list(self.smtp_config.get('apr_cc_recipients') or [])
        for address in candidates:
            clean = (address or '').strip()
            if not clean or clean.lower() in seen:
                continue
            seen.add(clean.lower())
            cc.append(clean)
        return cc

    def _deliver(self, msg, recipients: list, label: str) -> bool:
        """Open one SMTP session and send an assembled message."""
        try:
            with smtplib.SMTP(self.smtp_config['host'], self.smtp_config['port']) as server:
                server.starttls()
                server.login(self.smtp_config['user'], self.smtp_config['password'])
                server.send_message(msg)
            logger.info(f"{label} sent to {recipients}")
            return True
        except Exception as e:
            logger.error(f"Failed to send {label}: {e}", exc_info=True)
            return False

    def _shell(self, title: str, inner_html: str) -> str:
        """Wrap body content in the shared branded frame used by lifecycle emails."""
        return f"""<!DOCTYPE html>
<html>
<head><style>{self._LIFECYCLE_STYLE}</style></head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎭 SPIC MACAY</h1>
            <p>Society for the Promotion of Indian Classical Music And Culture Amongst Youth</p>
        </div>
        <div class="content">
            <h2 style="color:#8B0000; font-size:18px; margin-top:0;">{title}</h2>
            {inner_html}
        </div>
        <div class="footer">
            <p>This is an automated email from the SPIC MACAY Supatra Platform.</p>
            <p>&copy; {datetime.now().year} SPIC MACAY. All rights reserved.</p>
        </div>
    </div>
</body>
</html>"""

    def send_pre_event_guidelines(self, event_data: dict, recipients: list,
                                  guidelines_pdf_bytes: bytes = None,
                                  cc_recipients: list = None) -> bool:
        """
        Send the host institution its pre-programme SOP and checklist. Only meaningful
        before the programme takes place, so callers must gate this on a future date.

        The checklist is written into the body as well as attached, so it stays readable
        where the attachment is stripped or ignored.
        """
        if not self.enabled:
            logger.info("Email notifications disabled, skipping pre-event guidelines")
            return False

        institution = event_data.get('institution_name') or 'your institution'
        contact = (event_data.get('institute_coordinator_name') or '').strip()
        salutation = f"Dear {contact}," if contact else "Dear Sir/Madam,"
        coordinator_name = event_data.get('coordinator_name') or 'SPIC MACAY Team'
        chapter = event_data.get('chapter') or ''

        accompanying = (event_data.get('accompanying_artists') or '').strip()
        accompanying_row = (
            f'<tr><td class="label">Accompanying Artists</td><td>{accompanying}</td></tr>'
            if accompanying else ''
        )
        art_form_suffix = f" — {event_data.get('art_form')}" if event_data.get('art_form') else ''
        attach_note = ('<p class="attach-note">📎 The complete guidelines are attached as a PDF.</p>'
                       if guidelines_pdf_bytes else '')

        inner = f"""
            <p>{salutation}</p>
            <span class="pill">📅 Upcoming Programme</span>
            <p>Greetings from SPIC MACAY! We are delighted to confirm the following programme
               at {institution}.</p>

            <div class="facts">
                <table>
                    <tr><td class="label">Programme</td><td>{event_data.get('module_name') or 'Programme'}</td></tr>
                    <tr><td class="label">Artist</td><td>{event_data.get('artist_name') or 'N/A'}{art_form_suffix}</td></tr>
                    {accompanying_row}
                    <tr><td class="label">Date</td><td>{self._fmt_date(event_data.get('event_date'))}</td></tr>
                    <tr><td class="label">Time</td><td>{event_data.get('event_time') or 'To be confirmed'}</td></tr>
                    <tr><td class="label">Venue</td><td>{event_data.get('venue') or institution}</td></tr>
                </table>
            </div>

            <p>To help the session run beautifully, here is a short summary of what we request
               from the host institution.</p>

            <div class="sop">
                <h3>Travel</h3>
                <ul>
                    <li>Please arrange a well-maintained vehicle to bring the artistes from their
                        place of stay to the venue, and to drop them back.</li>
                    <li>Senior students and/or faculty should escort the artistes.</li>
                    <li>Kindly ensure the artistes reach the venue one hour before the scheduled start.</li>
                </ul>

                <h3>Green Room</h3>
                <ul>
                    <li>A clean, private green room near the auditorium, preferably with an attached
                        toilet and curtained windows.</li>
                    <li>Floor seating (darees or carpets covered with white sheets), plus a table and
                        three or four chairs to the side.</li>
                    <li>Drinking water and glasses. The room should be lockable so instruments can be
                        left safely.</li>
                </ul>

                <h3>Stage &amp; Sound</h3>
                <ul>
                    <li>An appropriate stage, with no cloth or carpet covering it. It may be decorated
                        with flowers, rangoli and diyas.</li>
                    <li>Only the SPIC MACAY third-eye logo on the backdrop — no other banners or
                        posters on stage or in the auditorium.</li>
                    <li>Sound system provided by the institution. Typical requirement: tabla 1 mike,
                        vocal and harmonium 2 mikes, sitar 1 mike, announcements 2 stand mikes,
                        dance 2 high-quality foot mikes. Full, normal stage lighting and four bottles
                        of mineral water.</li>
                    <li>Baithak-style seating in a closed auditorium is ideal, with students seated
                        close to the artistes.</li>
                </ul>

                <h3>During the Programme</h3>
                <ul>
                    <li>Starting on time is crucial. The programme may open with lamp lighting by the
                        head of the institution along with the artiste.</li>
                    <li>The compere should have the artiste's bio-data, reconfirmed with them
                        beforehand, and should check the correct sequence for introducing and
                        felicitating the artistes.</li>
                    <li>Mobile phones switched off, minimal movement, and no flash photography. Any
                        photography or video needs the artistes' prior consent.</li>
                    <li>A 15-minute interactive question-and-answer session closes the programme,
                        followed by felicitation of all artistes and a vote of thanks.</li>
                </ul>

                <h3>Hospitality &amp; Acknowledgement</h3>
                <ul>
                    <li>Light refreshments before and/or after the concert, and breakfast or lunch for
                        the artistes as appropriate. Students serving the artistes themselves adds a
                        lovely touch.</li>
                    <li>Bottled water and glasses on or near the stage during the programme.</li>
                    <li>Afterwards, a Letter of Acknowledgement on institution letterhead, signed by
                        the head of the institution, to be handed to the SPIC MACAY volunteer.</li>
                </ul>
            </div>

            {attach_note}

            <p>Please do reach out if anything above needs discussion — we are glad to help.</p>

            <p style="margin-top: 22px;">
                Warm regards,<br>
                <strong>{coordinator_name}</strong><br>
                SPIC MACAY{f' {chapter}' if chapter else ''}
            </p>
        """

        try:
            msg = MIMEMultipart('mixed')
            msg['Subject'] = (f"SPIC MACAY Programme Confirmation & Pre-Event Guidelines — "
                              f"{institution}")
            msg['From'] = self.smtp_config['from_email']
            msg['To'] = ', '.join(recipients)
            cc_list = self._outbound_cc(recipients, *(cc_recipients or []))
            if cc_list:
                msg['Cc'] = ', '.join(cc_list)
            msg.attach(MIMEText(
                self._shell('Programme Confirmation &amp; Pre-Event Guidelines', inner), 'html'
            ))

            if guidelines_pdf_bytes:
                try:
                    part = MIMEBase('application', 'pdf')
                    part.set_payload(guidelines_pdf_bytes)
                    encoders.encode_base64(part)
                    part.add_header('Content-Disposition', 'attachment',
                                    filename='SPIC_MACAY_Event_Guidelines.pdf')
                    msg.attach(part)
                except Exception as e:
                    logger.warning(f"Failed to attach guidelines PDF: {e}")

            return self._deliver(msg, list(recipients) + cc_list, "pre-event guidelines")
        except Exception as e:
            logger.error(f"Failed to build pre-event guidelines email: {e}", exc_info=True)
            return False

    def send_artist_apr_acknowledgement(self, event_data: dict, recipients: list) -> bool:
        """
        Thank the artist once their APR has been raised. Deliberately warm rather than
        administrative — the finance-facing detail belongs in the coordinator's copy.
        """
        if not self.enabled:
            logger.info("Email notifications disabled, skipping artist acknowledgement")
            return False

        artist_name = event_data.get('artist_name') or 'Artist'
        coordinator_name = event_data.get('coordinator_name') or 'SPIC MACAY Team'
        chapter = event_data.get('chapter') or ''
        institution = event_data.get('institution_name') or 'the host institution'

        feedback_url = (self.smtp_config.get('feedback_form_url') or '').strip()
        feedback_block = f"""
            <p>If you have a few minutes, we would love to hear how the session went from your side —
               your observations genuinely shape how we plan future programmes:<br>
               <a href="{feedback_url}" style="color:#B3161C; font-weight:700;">Share your feedback</a></p>
        """ if feedback_url else """
            <p>If you have a few minutes, we would love to hear how the session went from your side —
               simply reply to this email with your thoughts.</p>
        """

        inner = f"""
            <p>Dear {artist_name},</p>
            <span class="pill">🙏 With Gratitude</span>
            <p>Thank you for performing for SPIC MACAY at {institution}. Sharing your art with
               students is what this movement exists for, and we are grateful you gave your time
               and music to them.</p>

            <div class="facts">
                <table>
                    <tr><td class="label">Programme</td><td>{event_data.get('module_name') or 'Programme'}</td></tr>
                    <tr><td class="label">Institution</td><td>{institution}</td></tr>
                    <tr><td class="label">Date</td><td>{self._fmt_date(event_data.get('event_date'))}</td></tr>
                    <tr><td class="label">Reference No.</td><td>{event_data.get('request_id') or 'N/A'}</td></tr>
                </table>
            </div>

            <p>Your payment request has been raised with our office and is now being processed.
               We will write to you again as soon as the payment has been released — there is
               nothing you need to do in the meantime.</p>

            {feedback_block}

            <p>We hope to have the pleasure of hosting you again soon.</p>

            <p style="margin-top: 22px;">
                Warm regards,<br>
                <strong>{coordinator_name}</strong><br>
                SPIC MACAY{f' {chapter}' if chapter else ''}
            </p>
        """

        try:
            msg = MIMEMultipart('mixed')
            msg['Subject'] = "Thank You for Your Programme — SPIC MACAY"
            msg['From'] = self.smtp_config['from_email']
            msg['To'] = ', '.join(recipients)
            cc_list = self._outbound_cc(recipients, event_data.get('coordinator_email'))
            if cc_list:
                msg['Cc'] = ', '.join(cc_list)
            msg.attach(MIMEText(self._shell('Thank You for Your Programme', inner), 'html'))
            return self._deliver(msg, recipients + cc_list, "artist APR acknowledgement")
        except Exception as e:
            logger.error(f"Failed to build artist acknowledgement email: {e}", exc_info=True)
            return False

    def send_payment_completed_artist(self, payment_data: dict, recipients: list) -> bool:
        """Tell the artist their payment has been released."""
        if not self.enabled:
            logger.info("Email notifications disabled, skipping artist payment confirmation")
            return False

        artist_name = payment_data.get('artist_name') or 'Artist'
        institution = payment_data.get('institution_name') or 'the host institution'

        detail_rows = ''
        method = str(payment_data.get('payment_method') or '').strip()
        if method and method.lower() not in ('none', 'null'):
            detail_rows += f'<tr><td class="label">Mode</td><td>{method}</td></tr>'
        txn = str(payment_data.get('txn_id') or '').strip()
        if txn and txn.lower() not in ('none', 'null'):
            detail_rows += f'<tr><td class="label">Reference</td><td>{txn}</td></tr>'

        inner = f"""
            <p>Dear {artist_name},</p>
            <span class="pill">✅ Payment Released</span>
            <p>We are happy to let you know that the payment for your programme has been
               released by our office.</p>

            <div class="amount-box">
                <div class="label">Amount Released</div>
                <div class="value">{self._fmt_amount(payment_data.get('artist_payment'))}</div>
            </div>

            <div class="facts">
                <table>
                    <tr><td class="label">Programme</td><td>{payment_data.get('module_name') or 'Programme'}</td></tr>
                    <tr><td class="label">Institution</td><td>{institution}</td></tr>
                    <tr><td class="label">Programme Date</td><td>{self._fmt_date(payment_data.get('start_date'))}</td></tr>
                    <tr><td class="label">Released On</td><td>{self._fmt_date(payment_data.get('paid_on'))}</td></tr>
                    {detail_rows}
                </table>
            </div>

            <p>Depending on your bank, the credit may take a couple of working days to appear.
               If you do not see it after that, please do write to us and we will follow it up.</p>

            <p>Thank you once again for sharing your art with our students.</p>

            <p style="margin-top: 22px;">
                Warm regards,<br>
                <strong>SPIC MACAY</strong>
            </p>
        """

        try:
            msg = MIMEMultipart('mixed')
            msg['Subject'] = "Your SPIC MACAY Programme Payment Has Been Released"
            msg['From'] = self.smtp_config['from_email']
            msg['To'] = ', '.join(recipients)
            cc_list = self._outbound_cc(recipients, payment_data.get('coordinator_email'))
            if cc_list:
                msg['Cc'] = ', '.join(cc_list)
            msg.attach(MIMEText(self._shell('Payment Released', inner), 'html'))
            return self._deliver(msg, recipients + cc_list, "artist payment confirmation")
        except Exception as e:
            logger.error(f"Failed to build artist payment confirmation: {e}", exc_info=True)
            return False

    def send_payment_completed_coordinator(self, payment_data: dict, recipients: list) -> bool:
        """
        Confirm to the coordinator who filed the APR that finance has settled it — closing
        the loop on something they would otherwise keep chasing.
        """
        if not self.enabled:
            logger.info("Email notifications disabled, skipping coordinator payment confirmation")
            return False

        artist_name = payment_data.get('artist_name') or 'the artist'
        institution = payment_data.get('institution_name') or 'the host institution'
        artist_note = (
            'The artist has been informed directly as well.'
            if payment_data.get('artist_notified')
            else 'We do not have an email address on file for this artist, so they have not been '
                 'notified directly — you may wish to let them know.'
        )

        inner = f"""
            <p>Dear {payment_data.get('coordinator_name') or 'Coordinator'},</p>
            <span class="pill">✅ Settled by Finance</span>
            <p>The artist payment for the programme below has been completed by the finance team.
               No further follow-up is needed from your side.</p>

            <div class="amount-box">
                <div class="label">Amount Paid to Artist</div>
                <div class="value">{self._fmt_amount(payment_data.get('artist_payment'))}</div>
            </div>

            <div class="facts">
                <table>
                    <tr><td class="label">Artist</td><td>{artist_name}</td></tr>
                    <tr><td class="label">Programme</td><td>{payment_data.get('module_name') or 'Programme'}</td></tr>
                    <tr><td class="label">Institution</td><td>{institution}</td></tr>
                    <tr><td class="label">Programme Date</td><td>{self._fmt_date(payment_data.get('start_date'))}</td></tr>
                    <tr><td class="label">Paid On</td><td>{self._fmt_date(payment_data.get('paid_on'))}</td></tr>
                    <tr><td class="label">Reference No.</td><td>{payment_data.get('request_id') or 'N/A'}</td></tr>
                </table>
            </div>

            <p>{artist_note}</p>

            <p style="margin-top: 22px;">
                Warm regards,<br>
                <strong>SPIC MACAY Supatra Platform</strong>
            </p>
        """

        try:
            msg = MIMEMultipart('mixed')
            msg['Subject'] = f"Artist Payment Completed — {artist_name} ({institution})"
            msg['From'] = self.smtp_config['from_email']
            msg['To'] = ', '.join(recipients)
            # Central team is copied here too, so the office sees the loop closed even
            # though this one is addressed to the coordinator rather than outward
            cc_list = self._outbound_cc(recipients)
            if cc_list:
                msg['Cc'] = ', '.join(cc_list)
            msg.attach(MIMEText(self._shell('Artist Payment Completed', inner), 'html'))
            return self._deliver(msg, recipients + cc_list, "coordinator payment confirmation")
        except Exception as e:
            logger.error(f"Failed to build coordinator payment confirmation: {e}", exc_info=True)
            return False
