# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Test with real database
"""

from database import DatabaseManager
from dotenv import load_dotenv

load_dotenv()

print("🧪 Testing Real Database Connection\n")
print("="*80)

# Test database
db = DatabaseManager()

if db.connect():
    print("\n✅ Database connection successful!\n")
    
    # Test 1: Get event modules
    print("📋 Event Modules:")
    print("-"*80)
    modules = db.get_event_modules()
    for m in modules:
        print(f"  {m['tid']}: {m['name']}")
    
    # Test 2: Get some artists
    print("\n🎨 Sample Artists (Hindustani):")
    print("-"*80)
    artists = db.get_artists('Hindustani')[:5]
    for a in artists:
        print(f"  {a['tid']}: {a['name']} - {a['art_form']}")
    
    # Test 3: Get some institutions
    print("\n🏛️ Sample Institutions (Delhi):")
    print("-"*80)
    institutions = db.get_institutions('Delhi')[:5]
    for i in institutions:
        print(f"  {i['sid']}: {i['institution_name']} - {i['city']}")
    
    # Test 4: Save a test event
    print("\n💾 Testing Event Save:")
    print("-"*80)
    
    test_event = {
        'title': 'Test Bot Event - Kathak Workshop',
        'start_date': '2025-03-20',
        'end_date': '2025-03-20',
        'start_time': '14:00',
        'end_time': '16:00',
        'event_category': 4,  # Lecture Demonstration
        'state': 'Delhi',
        'city': 'New Delhi',
        'institution_name': 'Test Institution via Bot',
        'artist_id': None,
        'venue': 'Test Auditorium',
        'attendees': '150',
        'budget': 0.0,
        'added_by': 0
    }
    
    event_id = db.save_event(test_event)
    
    if event_id:
        print(f"✅ Test event created with ID: {event_id}")
        
        # Retrieve it back
        saved_event = db.get_event_by_id(event_id)
        if saved_event:
            print("\n✅ Event retrieved successfully:")
            print(f"  Title: {saved_event['title']}")
            print(f"  Date: {saved_event['start_date']}")
            print(f"  Institution: {saved_event['institution']}")
            print(f"  Status: {saved_event['event_status']}")
    
    db.disconnect()
    print("\n" + "="*80)
    print("✅ All tests passed!")
else:
    print("❌ Database connection failed!")

print("="*80 + "\n")
